### ISSUE TITLE
Repositorio de Documentación, con archivos e Imagenes de Modelo de Datos y Mockups  

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/Financiera_documentacion#1]
crear repositorio con documentación de modelos de datos y mockups de lo que se ha hecho de plan de cuentas (rubros, apropiaciones, fuentes) 8 horas-- Carlos
- [x] crear repositorio
- [x] incluir readme
- [x] incluir imágenes de modelos de datos y documentación
- [x] incluir imágenes de mockups y documentación

**Comment by Soulfilip-UD** [comment]
EL repositorio contiene la información general de todos los mockups y modelos de datos que hasta el momento se han venido trabajando correctamente, recomiendo adjuntar los archivos de los modelos de datos en el repositorio y en caso de que los mockups de apropiaciones esten contenidos dentro de los mockups de rubros especificar en el readme expuesto tal información o eliminar el link en el README general

**Comment by Soulfilip-UD** [comment]
Tarea Finalizada y muy bien realizada
Proceeding to close Issue :space_invader:
