### ISSUE TITLE
Desarrollo de los mockups para CDP y, CRP - Solicitud

### ISSUE THREAD

**Issue by macaguegi** [udistrital/financiera_documentacion#13]
Se solicita desarrollar mockups para CDP's y CRP's : 

- [x] Realizar análisis de HU y documentos realizados por analista 

- [x] Socializar dudas 

- [x] Diseñar y construir los mockups para Solicitar CRP en Draw.io 
- [x] Diseñar y construir los mockups para Consultar Solicitudes de  CRP en Draw.io 
- [x] Diseñar y construir los mockups para Expedir CRP en Draw.io 

- [x] Documentar los mockups

**Comment by macaguegi** [comment]
Hoy se realiza lectura y análisis de las Historias de Usuario que han sido proporcionadas por la analista @mcrubianot . Estado de la tarea : 15%.

**Comment by macaguegi** [comment]
Se empieza el diseño y construcción de los mockups en la herramienta Draw.io 
[Mockups CDP y CRP](https://drive.google.com/file/d/10xroOR9JWO_C-uvoqFlHCttXUw_PP3oJ/view?usp=sharing) . Además se realiza socialización con analista @mcrubianot para comprender la lógica de negocio . Estado de la tarea : 30%

**Comment by macaguegi** [comment]
Se socializan mockups con analista @mcrubianot de lo cual se realizan las siguientes observaciones 

- [ ] La parte de financiación debe tener el Nombre del parámetro y el valor

- [ ] Es importante visualizar quien elaboró el documento (CRP)

- [ ] Se habla de un rechazo del CRP no una anulación

- [ ] Para el sprint del viernes se debe consultar sobre los tipos de compromisos y sus respectivos números. Tarea a cargo de analista @mcrubianot

**Comment by macaguegi** [comment]
Se concluye esta tarea con un estado del 100% . Se solicita revisión por parte de líder técnico @Soulfilip-UD . Los mockups se encuentran en [Mockups](https://github.com/udistrital/financiera_documentacion/blob/f/crp/plan_cuentas/CDP-CRP/mockups.md)

**Comment by Soulfilip-UD** [comment]
Revisando la tarea @macaguegi el link que adjuntas debe actualizarse con este [Mockups](https://github.com/udistrital/financiera_documentacion/blob/master/plan_cuentas/CDP-CRP/mockups.md), posiblemente cambiaste el nombre de la carpeta. Revisa asimismo las imagenes adjuntadas para CRP ya que no están cargando. Quedo pendientes de los cambios.

**Comment by Soulfilip-UD** [comment]
Se revisa las correcciones realizadas y los mockups se encuentran todos en el anterior link.

Tarea revisada y finalizada
Proceeding to close Issue 👾
