### ISSUE TITLE
Reunión SGA - Kronos: Gestión de Avances

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_documentacion#148]
Se realiza mesa de trabajo con la ingeniera Ma. Fernanda Avendaño, con el fin de presentarle las historias de usuario (mockups) de la Gestión de Avances prevista para el Sistema Kronos y validar que interoperabilidad se daría entre dicho proceso y el de Prácticas Académicas establecido en los procesos de Académica.

**Comment by mafeave** [comment]
Se comparte por parte de @mcrubianot el [procedimiento ](http://sigud.udistrital.edu.co/vision/filesSIGUD/SIGUD%202018/Gestion%20de%20Recursos%20Financieros/GRF-PR-012/#diagram/f103f5ae-f63f-45e9-b04a-8d0ce4994716)definido en el SIGUD para la gestión de avances y  los [mockups ](https://drive.google.com/file/d/1bDDnzat6E4cjavx_gICzEN468ffNPdRW/view?ts=5fac571b) definidos para el desarrollo en Kronos. Tener presente que los campos en color corresponden a listas desplegables.

Las prácticas académicas son un Tipo de Avance.

Desde Tesorería se registran los tipos de avance, los requisitos (soportes) necesarios para solicitar un avance y se realiza la asociación de los requisitos necesarios para cada tipo de avance.

Para la realización de una solicitud de avance, el docente o funcionario de planta debe relacionar el Ordenador del Gasto
No se aprobará una solicitud de avance, mientras el docente tenga algún avance sin legalizar.

Revisar ejemplos de resoluciones para las prácticas académicas desde la página de la secretaría general.

Se tiene un plazo de 15 días hábiles para realizar la legalización del avance.
El docente debe hacer la consignación del dinero que le haya sobrado después de realizar la práctica académica.
Para la legalización del avance, el docente debe enviar a través de un oficio los gastos asociados, y tesorería los registra en el sistema. Tener en cuenta que los proveedores relacionados deben estar registrados en el sistema (terceros), y se deben relacionar los porcentajes correspondientes de retención.
Tesorería realiza las actas de reembolso y los comprobantes de contabilidad.
Para la legalización de la práctica académica se debe relacionar el listado de los estudiantes relacionados de acuerdo al formato definido en el SIGUD.

Finalmente desde el rol de Asistente de Tesorería se podrá consultar el detalle de cada uno de los avances realizados.

Flujo General del avance: 
1. Realización y verificación de la solicitud 
2. Expedición de la necesidad, expedición de CDP, generar resolución de aprobación de avance, elaboración de la orden de pago, realización del giro.
3. Legalización del avance

La contratación de transporte relacionado en el procedimiento de Práctica Académicas, se debe realizar desde el módulo de presupuesto de Kronos.
