### ISSUE TITLE
Desarrollo de los mockups para CDP y, CRP - expedicion 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/financiera_documentacion#15]
- [x] Aclarar con analista flujo CDP
- [x] Aclarar con analista flujo CRP
- [x] Aclarar con analista requerimientos de historias de usuario
- [x] Verificacion versiones anteriores
- [x] Bosquejo mockup y solicitud de diseño, revision

**Comment by CarlosGutierrezArdila** [comment]
9/9/19:  se analizan Historias de usuario, avance 5%

**Comment by CarlosGutierrezArdila** [comment]
11/9/2019: atendiendo a las recomendaciones de analista y a lo socializado se finaliza el diseño de los mockups correspondientes, avance 100%

**Comment by Soulfilip-UD** [comment]
Se tiene en cuenta la información socializada en el Issue #19 

Revisando la tarea @CarlosGutierrezArdila  el link de los mockups es [Mockups](https://github.com/udistrital/financiera_documentacion/blob/master/plan_cuentas/CDP-CRP/mockups.md). 
Revisar asimismo las imagenes adjuntadas para CRP ya que no están cargando. Quedo pendientes de los cambios.

**Comment by Soulfilip-UD** [comment]
Se revisa las correcciones realizadas y los mockups se encuentran todos en el anterior link.

El seguimiento para la socialización de los mockups es el siguiente #25 

Tarea revisada y finalizada
Proceeding to close Issue 👾
