### ISSUE TITLE
Capacitación al equipo de kronos sobre el padron Redux y Ngrx

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/financiera_documentacion#159]
realizar capacitación al equipo de kronos sobre la teoría e implementan del patrón redux usando Ngrx en angular 8 de tal manera que permita a los demás miembros del equipo el poder implementarlo en los desarrollos nuevos

**Comment by ManuelMurillo** [comment]
Se desarrolla la capacitacion con el siguiente repositorio plantilla del Plan de Adquisiciones https://github.com/ManuelMurillo/plan_adquisiciones_cliente/tree/ClaseRedux/02/12/2020.
Se crea una presentacion correspondiente al marco teorico del patron para uso general por parte de las personas que lo necesiten https://slides.com/jhoanm/redux-pattern.
La practica se desarrolla en base al siguiente mockup:
https://drive.google.com/file/d/12BTXAaKUVoDUU2UcaRo8NfLri6A7IEM5/view?usp=sharing

**Comment by ManuelMurillo** [comment]
Mockup:
![Capacitacion Redux Peliculas-Diseño de Vista](https://user-images.githubusercontent.com/29108085/101280858-925ca080-3799-11eb-946a-3182ebe07a49.png)
Arbol de Componentes:
![Capacitacion Redux Peliculas-Arbol de Componentes](https://user-images.githubusercontent.com/29108085/101280853-896bcf00-3799-11eb-94c6-bc70644082bd.png)
