### ISSUE TITLE
Desarrollo de mockups para modificación presupuestal - 5 horas- Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/financiera_documentacion#16]
- [x] Generar diseño de mockup para interface de modificaciones presupuestales.

**Comment by miguelramirez93** [comment]
Se agrega mockup en formato xml para poder modificarlo mas adelante. los diseños de los mockup's se pueden ver mas comodamente en : https://drive.google.com/file/d/15NPQQImfPr2EmWjsuWwMynRwZYbm4Oqn/view?usp=sharing

**Comment by Soulfilip-UD** [comment]
Se revisaron los mockups, aunque por facilidad de que si reciben modificaciones se puedan ver mas adelante, anexar un archivo pdf con los mockups a la fecha. 
Asimismo @miguelramirez93  recomiendo ir realizando la documentación en el repositorio con el readme y los archivos en imágenes. Conservo la tarea en DOING hasta cuando se realice la socialización.

**Comment by miguelramirez93** [comment]
@Soulfilip-UD se realiza modificación de los mup's según lo propuesto por @mcrubianot en el issue #23

**Comment by mcrubianot** [comment]
Ingeniero Miguel, considero que de acuerdo a lo establecido en el procedimiento y el caso de uso está bien. Debemos tener claro que la Oficina Asesora de Planeación es quien solicita a presupuesto la modificación en el sistema. Por ahora el actor directo debe ser presupuesto. quien puede registrar y consultar. el documento oficial de las modificaciones es una Resolución que firma el CSU. y el trámite considero no puede ser devuelto.

**Comment by Soulfilip-UD** [comment]
Los mockups son acordes, ya se deben revisar en una socialización con el analista y en caso que deban realizarse ajustes, se daran sobre dicho Issue .
Tarea finalizada

Proceeding to close Issue 👾

**Comment by miguelramirez93** [comment]
Se realiza la actualización de la documentación . tarea finalizada @Soulfilip-UD
