### ISSUE TITLE
listar apis a las cuales se les debe actualizar el drone

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/financiera_documentacion#167]
ya que algunas apis no dan conflicto de código y pueden unificarse para su despliegue con el código de la oficina asesora de sistemas se ha de realizar una lista de los repositorios que deben de recibir una actualizaron en drone y posiblemente en otros archivos según los estándares de la oficina asesora de sistemas

**Comment by BOTOOM** [comment]
| Repositorio | Rama con últimos cambios |
| :------- | :------: |
| [programa_academico_crud](https://github.com/udistrital/programa_academico_crud)   | test       |

**Comment by BOTOOM** [comment]
@jjvargass

**Comment by jjvargass** [comment]
Se realiza configuración de repo evaluacion_inscripcion_crud:
Se realiza limpieza de carpeta swagger
Se actualiza README
Se actualiza pipeline para registra imagen ahora en ECR.
Solicitar a @BrayanB24  actualizar el ECS "servicio" para que tome la imagen que ahora esta en ECR AWS.
