### ISSUE TITLE
analizar api de movimientos y base de datos que analizar movimientos y como estos datos son usados

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/financiera_documentacion#171]
se requiere revisar el funcionamiento del api de movimientos y su uso con la finalidad de dar claridad al avance del sistema central de cuentas

para ello se requiere lo siguiente: 

- [x] revisar el api de movimientos_crud y la base de datos que consume (es postgres).
- [x] revisar la base de datos de mongo si llega a ser utilizada ya que existen datos alli. 
- [x] revisar los movimientos realizados sobre un rubro donde son almacenados y procesados

**Comment by NRDaza** [comment]
Se realiza una revisión en la base de datos de pruebas para mirar que datos contiene relacionado con la api de `movimientos `o cosas relacionadas con `movimiento`, únicamente se encuentre el schema de movimientos el cual contiene las mismas tablas con la misma estructura. 
![busquedabase1](https://user-images.githubusercontent.com/34488581/103785441-3049c200-5009-11eb-8d7a-c8d30ee0b043.PNG)

Las tablas de `movimientos_detalle `y `movimiento_proceso_externo` tiene almacenados registros de pruebas y la tabla `tipo_movimiento` contiene otros datos no incluidos en las migraciones del api de movimientos.
![busquedabase1_tipoMovimiento](https://user-images.githubusercontent.com/34488581/103785725-8f0f3b80-5009-11eb-9652-3041e5df4769.PNG)

**Comment by NRDaza** [comment]
# Plan_cuentas_mongo_crud
## Rutas 
Existe una ruta `./v1/movimiento` la cual usa al controlador `MovimientosController`, esta incluye además los siguientes métodos:
```
Method: "GetMovimientosByDocumentoPresupuestalUUID",
Router: `/:vigencia/:CG/:parentUUID`,
Tipo: GET
```
```
Method: "RegistrarMovimientoParameter",
Router: `/RegistrarMovimientoParameter`,
Tipo: POST
```
```
Method: "RegistrarMovimiento",
Router: `/RegistrarMovimientos`,
Tipo: POST
```
## Controlador
Se tiene un único controlador `movimientos.go` el cual contiene los métodos mencionadas en las rutas cada uno de estos métodos contiene la siguiente descripción

`GetMovimientosByDocumentoPresupuestalUUID `: función para obtener todos los objetos por parentUUID.

`RegistrarMovimientoParameter`:  Registra los movimientos (como cdp, rp, ver variable tipoMovimiento) y los propaga tanto en la colección arbolrubrosapropiacion_[vigencia]_[unidad_ejecutura], como en la colección movimientos. Utiliza la función registrarValores para registrar los valores, y se le envían como parámetro el nombre de los movimientos que se van a guardar en el atributo movimiento de la colección arbolrubrosapropiacion, al igual que se envía la variable dataValor, que son los valores del movimiento enviados desde el api_mid_financiera.

`RegistrarMovimiento`:  Registra los movimientos (como cdp, rp, ver variable tipoMovimiento) y los propaga tanto en la colección arbolrubrosapropiacion_[vigencia]_[unidad_ejecutura], como en la colección movimientos. Utiliza la función registrarValores para registrar los valores, y se le envían como parámetro el nombre de los movimientos que se van a guardar en el atributo movimiento de la colección arbolrubrosapropiacion, al igual que se envía la variable dataValor, que son los valores del movimiento enviados desde el api_mid_financiera
## Manager
En el archivo `movimiento.manager.go` se encuentran la mayoría de funciones relacionada con movimientos para hacer las consultas a mongo, en general se usan para la construcción de un documento presupuestal.:


- `GetOneMovimientoByTipo`: Realiza consulta a Mongo a la colección `MovimientoParameterCollection `, según `_id` y `tipo `. No usada.

- `GetOneMovimientoParameterByHijo`: Realiza consulta a Mongo a la colección `MovimientoParameterCollection `, según `tipo_movimiento_hijo `  .Usada en `movimiento.helper.go` para la función `BuildPropagacionValoresTr` que se encarga de la construcción de una transacción para  el registro de un documento presupuestas en la función `DocumentoPresupuestalRegister` del `movimiento.compositor.go`,  la función `BuildPropagacionValoresTr`  además es usada en la comprobación de balance del árbol de apropiaciones `ComprobarBalanceArbolApropiaciones()` en el controlador `arbol_rubro_apropiacion.go`.

- `GetInitialMovimientoParameterByHijo `:  Realiza consulta a Mongo a la colección `MovimientoParameterCollection `, según `tipo_movimiento_hijo ` y `"initial": true` .Usadas también en las funciones `DocumentoPresupuestalRegister()` y `BuildPropagacionValoresTr ()`.

- `GetOneMovimientoParameterByHijoAndPadre`: Realiza consulta a Mongo a la colección `MovimientoParameterCollection `, según `tipo_movimiento_hijo ` y `tipo_movimiento_padre` .Usada  en la función `BuildPropagacionValoresTr `.

- SaveMovimientoParameter: Ingresa un movimiento a la colección en mongo `MovimientoParameterCollection . `Usada en el método  `RegistrarMovimientoParameter` del controlador `movimientos.go`.

- `GetAllMovimiento`: Regresa todos los movimientos de la colección `MovimientosCollection_"vigencia"_"cg"`. Usada en la construcción de documento presupuestal 

- `GetMovimientoByDocumentoPresupuestalUUID`: Regresa la información de un movimiento usando la `vigencia`, `centro gestor` y `ParentUUID   ` de la colección MovimientosCollection .Usada en el método `GetMovimientosByDocumentoPresupuestalUUID `del controlador `movimiento.go`

- GetOneMovimientoByID: Regresa la información de un movimiento según su `_Id` en mongo.

- `GetAllMovimientoByParentUUID`: Regresa información de un movimiento según `Id `del `padre` de la colección `MovimientosCollection`


## Modelos
Esta api tiene dos modelos relacionados con movimientos `movimientos.go` y `tr_movimientos`.
El modelo movimientos.go tiene las siguientes 3 estructuras y hace uso de la colección en mongo llamada `MovimientosCollection ` y `MovimientoParameterCollection `:
```
type Movimiento struct {
	ID                        string             `json:"_id" bson:"_id,omitempty"`
	IDPsql                    int                `json:"IDPsql" bson:"id_psql" validate:"required"`
	Tipo                      string             `json:"Tipo" bson:"tipo" validate:"required"`
	DocumentoPresupuestalUUID string             `json:"DocumentoPresupuestalUUID" bson:"documento_presupuestal_uuid"`
	Padre                     string             `json:"Padre" bson:"padre"`
	FechaRegistro             string             `json:"FechaRegistro" bson:"fecha_registro" validate:"required"`
	Movimientos               map[string]float64 `json:"Movimientos" bson:"movimientos"`
	Estado                    string             `json:"Estado" bson:"estado"`
	ValorActual               float64            `json:"ValorActual" bson:"valor_actual"`
	ValorInicial              float64            `json:"ValorInicial" bson:"valor_inicial"`
	DocumentosPresGenerados   *[]string          `json:"DocumentosPresGenerados" bson:"documentos_pres_generados,omitempty"`
}

// MovimientoParameter this struct represent a "movmientos_parametros" collection item.
type MovimientoParameter struct {
	ID                     string  `json:"_id" bson:"_id,omitempty"`
	TipoMovimientoHijo     string  `json:"TipoMovimientoHijo" bson:"tipo_movimiento_hijo"`
	TipoMovimientoPadre    string  `json:"TipoMovimientoPadre" bson:"tipo_movimiento_padre"`
	Multiplicador          int     `json:"Multiplicador" bson:"miltiplicador"`
	FatherCollectionName   string  `json:"FatherCollectionName" bson:"father_collection_name"`
	FatherUUIKeyName       string  `json:"FatherUUIKeyName" bson:"father_uuikey_name"`
	Initial                bool    `json:"Initial" bson:"initial"`
	WithOutChangeState     bool    `json:"WithOutChangeState" bson:"without_change_state"`
	TipoDocumentoGenerado  *string `json:"TipoDocumentoGenerado" bson:"tipo_documento_generado,omitempty"`
	NoBalanceLeftStateName *string `json:"NoBalanceLeftStateName" bson:"no_balance_left_state_name,omitempty"`
}

// AfectacionMovimiento this struct will save modification's movs for test their behaivor before save on db
type AfectacionMovimiento struct {
	CuentaCredito       *NodoRubroApropiacion `json:"cuenta_credito"`
	CuentaContraCredito *NodoRubroApropiacion `json:"cuenta_contra_credito"`
	Tipo                string                `json:"tipo"`
	Valor               float64               `json:"valor"`
}
```
Contiene una unica funcion `GetMovmientoByParentId` usada en el controlador del movimiento la cual regresa un movimiento según `vigencia`, `areafuncional `e `Id`.


Para el modelo `tr_movimientos.go` contiene únicamente una función `RegistrarMovimiento` que usan la colección en mongo de 
`TransactionCollection` pero no es usada en ninguna lado.
## Migraciones
Se menciona tipos de movimiento en las diferentes migraciones de la base de datos según el modelo `movimientos.go`, en ellos se crean tipos de movimiento de la siguiente forma:
```
AnulacionCdpToRp := models.MovimientoParameter{
  Multiplicador:          -1,
  TipoMovimientoHijo:     "anul_cdp",
  TipoMovimientoPadre:    "cdp",
  Initial:                true,
  NoBalanceLeftStateName: &anulateSTatus,
}
```
Se realiza lo mismo para:

- anulacionRpToRp
- AnulacionRpToCDP
- CreacionRp
- AnulacionCdpToApropiacion
- CreacionRp
- AnulacionRp
- AdicionApropiacion
- ReduccionApropiacion

Desde la migración 2 hasta la 6 se realizan modificación e ingreso de datos con los temas de RP, CDP, apropiaciones 

# Plan_cuentas_mid
## Rutas 
Existe una ruta `./v1/movimiento` la cual usa al controlador `MovimientosController`, esta incluye además los siguientes métodos:
```
Method: "Post",
Router: `/`,
Tipo: Post
```
```
Method: "GetAllAnulacionesByVigenciaCGAndUUID",
Router: `/get_doc_by_mov_parentUUID/:vigencia/:CG/:UUID`,
Tipo: GET
```
## APIS 
`financieraMongoCurdApiService = ${PLAN_CUENTAS_MONGO_CRUD}`: plan_cuentas_mongo_crud
`movimientosCrudService = ${MOVIMIENTOS_CRUD}` : movimientos_crud

## Controlador
Se tiene un único controlador `movimientos.go` el cual contiene los métodos mencionadas en las rutas cada uno de estos métodos contiene la siguiente descripción

- `Post` : Envia los datos relacionados con los movimientos al api `movimientos_crud `para ser almacenados en `postgres`, los datos son enviados al siguiente ENDPOINT `("movimientosCrudService")+"movimiento_detalle/registrar_multiple"`.A partir de los Id generados en postgrest los almacena en la data y la envia  a Mongo al ENDPOINT ` ("financieraMongoCurdApiService")+"movimiento/RegistrarMovimientos"`. Por último, si existe un error al ingresar los datos a mongo ,  elimina estos registros del api `movimientos_crud ` segun los Ids del primer registro, lo realiza al ENDPOINT `("movimientosCrudService")+"movimiento_detalle/eliminar_multiple"`

- `GetAllAnulacionesByVigenciaCGAndUUID`: Realiza una consulta al plan_cuentas_mongo_crud donde retorna un array de documentos presupuestales según la Vigencia, Centro Gestor y UUID, la consulta la realiza al ENDPOINT
`("financieraMongoCurdApiService") + "documento_presupuestal" + "/" + "get_doc_mov_by_parent/" + vigencia + "/" + cg + "/" +docUUID`

## Modelos 
Los modelos usados en los controladores son los siguientes:

`movimiento.go`
```
type Movimiento struct {
	Id                         int
	MovimientoProcesoExternoId *MovimientoProcesoExterno `validate:"required"`
	Valor                      float64                   `validate:"required"`
	FechaRegistro              string
	Descripcion                string `validate:"required"`
	DocumentoPadre             string
}

// MovimientoProcesoExterno ...
type MovimientoProcesoExterno struct {
	Id                       int
	TipoMovimientoId         *TipoGeneral `validate:"required"`
	ProcesoExterno           int64
	MovimientoProcesoExterno int
}

// MovimientoMongo ...
type MovimientoMongo struct {
	ID            string  `json:"_id" bson:"_id,omitempty"`
	IDPsql        int     `json:"IDPsql"`
	ValorInicial  float64 `json:"ValorInicial"`
	Tipo          string  `json:"Tipo"`
	Padre         string  `json:"Padre"`
	FechaRegistro string  `json:"FechaRegistro"`
	Descripcion   string  `json:"Descripcion"`
}
```
`documento_presupuestal.go`

```
type DocumentoPresupuestal struct {
	ID                   string            `json:"_id" bson:"_id,omitempty"`
	Data                 interface{}       `json:"Data" bson:"Data" validate:"required"`
	Tipo                 string            `json:"Tipo" bson:"Tipo" validate:"required"`
	AfectacionIds        []string          `json:"AfectacionIds" bson:"AfectacionIds"`
	Vigencia             int               `json:"Vigencia" bson:"Vigencia" validate:"required"`
	CentroGestor         string            `json:"CentroGestor" bson:"CentroGestor" validate:"required"`
	AfectacionMovimiento []Movimiento      `json:"AfectacionMovimiento" validate:"required"`
	Afectacion           []MovimientoMongo `json:"Afectacion"`
	FechaRegistro        string
	Consecutivo          int     `json:"Consecutivo" bson:"consecutivo"`
	ValorActual          float64 `json:"ValorActual" bson:"valor_actual"`
	ValorInicial         float64 `json:"ValorInicial" bson:"valor_inicial"`
}
```
# Presupuesto_cliente

Se realiza una búsqueda de los componentes que tenga relación con MOVIMIENTOS_CRUD_SERVICE:

Se encuentra que es usado en `modApropiaciónHelper.ts`, alli se realiza un `GET` del `tipo_movimiento` en la función `getModTypes()`, esta función es usada por el componente `set-modificacion-apropiacion.component.ts`, allí se realiza un filtro por el acrónimo del movimiento el cual retorna `true `en caso de pertenecer a  alguno de los siguientes tipos `adicion `,  `suspension `, `traslado `,`reduccion`. Los resultados del filtro se observa en el `set-modificacion-apropiacion.component.hmtl` en un `select` donde se muestran los tipos de modificación.

Se encuentra usado tambien en `modFuenteHelper.ts`, alli se realiza un `GET` del `tipo_movimiento/?limit=-1` en la función `getModTypes()`,  esta función es usada en el componente `set-modificacion-fuente.component.ts`, alli es realizado un filtro por el acronimo `"fuente"`, los resultados de esta consulta son mostrados en un `select `en el archivo `set-modificacion-fuente.component.html`
