### ISSUE TITLE
creación de plantilla para kamban de despliegue de apis de campus

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/financiera_documentacion#178]

**Comment by BOTOOM** [comment]
Buen dia Ingenieros.

Mediante el presente kamban solicito amablemente realizar el despliegue en el ambiente de pruebas el api de plan_adquisiciones_crud.

el repositorio del api esta en el siguiente link:

https://github.com/udistrital/plan_adquisiciones_crud

el repo ya fue activado en drone :

https://hubci.portaloas.udistrital.edu.co/udistrital/plan_adquisiciones_crud/


Las variables de entorno son las siguientes:

Environment:
- Name: AWS_DEFAULT_REGION
Value: us-east-1
- Name: PARAMETER_STORE
Value: preprod
- Name: PLAN_ADQUISICIONES_CRUD_HTTP_PORT
Value: 
- Name: PLAN_ADQUISICIONES_CRUD_RUN_MODE
Value: dev
- Name: PLAN_ADQUISICIONES_CRUD_PGHOST
Value: 
- Name: PLAN_ADQUISICIONES_CRUD_PGPORT
Value: 
- Name: PLAN_ADQUISICIONES_CRUD_PGDB
Value: 


estaré atento a cualquier novedad o comentario 

muchas gracias

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
ubicaciones_crud

•	Name: UBICACIONES_HTTP_PORT
Value: 8085
•	Name: UBICACIONES_CRUD__PGUSER
Value: 
•	Name: UBICACIONES_CRUD__PGPASS
Value: 
•	Name: UBICACIONES_CRUD__PGURLS
Value: 
•	Name: UBICACIONES_CRUD__PGDB
Value: 
•	Name: UBICACIONES_CRUD__SCHEMA
Value: 
•	Name: UBICACIONES_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
recibo_crud

•	Name: RECIBO_CRUD_HTTP_PORT
Value: 9017
•	Name: RECIBO_CRUD__PGUSER
Value: 
•	Name: RECIBO_CRUD__PGPASS
Value: 
•	Name: RECIBO_CRUD__PGURLS
Value: 
•	Name: RECIBO_CRUD__PGDB
Value: 
•	Name: RECIBO_CRUD__SCHEMA
Value: 
•	Name: RECIBO_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
programa_academico_crud

•	Name: PROGRAMA_ACADEMICO_HTTP_PORT
Value: 8101
•	Name: PROGRAMA_ACADEMICO_CRUD__PGUSER
Value: 
•	Name: PROGRAMA_ACADEMICO_CRUD__PGPASS
Value: 
•	Name: PROGRAMA_ACADEMICO_CRUD__PGURLS
Value: 
•	Name: PROGRAMA_ACADEMICO_CRUD__PGDB
Value: 
•	Name: PROGRAMA_ACADEMICO_CRUD__SCHEMA
Value: 
•	Name: PROGRAMA_ACADEMICO_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
produccion_academica_crud

•	Name: API_PRODUCCION_ACADEMICA_HTTP_PORT
Value: 9012
•	Name: PRODUCCION_ACADEMICA_CRUD__PGUSER
Value: 
•	Name: PRODUCCION_ACADEMICA_CRUD__PGPASS
Value: 
•	Name: PRODUCCION_ACADEMICA_CRUD__PGURLS
Value: 
•	Name: PRODUCCION_ACADEMICA_CRUD__PGDB
Value: 
•	Name: PRODUCCION_ACADEMICA_CRUD__SCHEMA
Value: 
•	Name: PRODUCCION_ACADEMICA_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
personas_crud

•	Name: API_PERSONAS_HTTP_PORT
Value: 8083
•	Name: PERSONAS_CRUD__PGUSER
Value: 
•	Name: PERSONAS_CRUD__PGPASS
Value: 
•	Name: PERSONAS_CRUD__PGURLS
Value: 
•	Name: PERSONAS_CRUD__PGDB
Value: 
•	Name: PERSONAS_CRUD__SCHEMA
Value: 
•	Name: PERSONAS_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
organizacion_crud

•	Name: ORGANIZACION_CRUD__HTTP_PORT
Value: 8097
•	Name: ORGANIZACION_CRUD__DB_USER
Value: 
•	Name: ORGANIZACION_CRUD__DB_PASS
Value: 
•	Name: ORGANIZACION_CRUD__DB_URL
Value: 
•	Name: ORGANIZACION_CRUD__DB_NAME
Value: 
•	Name: ORGANIZACION_CRUD__SCHEMA
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
inscripcion_crud

•	Name: INSCRIPCION_CRUD_HTTP_PORT
Value: 8887
•	Name: INSCRIPCION_CRUD__PGUSER
Value: 
•	Name: INSCRIPCION_CRUD__PGPASS
Value: 
•	Name: INSCRIPCION_CRUD__PGURLS
Value: 
•	Name: INSCRIPCION_CRUD__PGDB
Value: 
•	Name: INSCRIPCION_CRUD__SCHEMA
Value: 
•	Name: INSCRIPCION_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
idiomas_crud

•	Name: IDIOMAS_CRUD_HTTP_PORT
Value: 8103
•	Name: IDIOMAS_CRUD__PGUSER
Value: 
•	Name: IDIOMAS_CRUD__PGPASS
Value: 
•	Name: IDIOMAS_CRUD__PGURLS
Value: 
•	Name: IDIOMAS_CRUD__PGDB
Value: 
•	Name: IDIOMAS_CRUD__SCHEMA
Value: 
•	Name: IDIOMAS_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
forms_management_crud

•	Name: API_FORMS_MANAGEMENT_HTTP_PORT
Value: 9011
•	Name: FORMS_MANAGEMENT_CRUD__PGUSER
Value: 
•	Name: FORMS_MANAGEMENT_CRUD__PGPASS
Value: 
•	Name: FORMS_MANAGEMENT_CRUD__PGURLS
Value: 
•	Name: FORMS_MANAGEMENT_CRUD__PGDB
Value: 
•	Name: FORMS_MANAGEMENT_CRUD__SCHEMA
Value: 
•	Name: FORMS_MANAGEMENT_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
formacion_academica_crud

•	Name: FORMACION_ACADEMICA_HTTP_PORT
Value: 8098
•	Name: FORMACION_ACADEMICA_CRUD__PGUSER
Value: 
•	Name: FORMACION_ACADEMICA_CRUD__PGPASS
Value: 
•	Name: FORMACION_ACADEMICA_CRUD__PGURLS
Value: 
•	Name: FORMACION_ACADEMICA_CRUD__PGDB
Value: 
•	Name: FORMACION_ACADEMICA_CRUD__SCHEMA
Value: 
•	Name: FORMACION_ACADEMICA_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
experiencia_laboral_crud

•	Name: EXPERIENCIA_LABORAL_HTTP_PORT
Value: 8099
•	Name: EXPERIENCIA_LABORAL_CRUD__PGUSER
Value: 
•	Name: EXPERIENCIA_LABORAL_CRUD__PGPASS
Value: 
•	Name: EXPERIENCIA_LABORAL_CRUD__PGURLS
Value: 
•	Name: EXPERIENCIA_LABORAL_CRUD__PGDB
Value: 
•	Name: EXPERIENCIA_LABORAL_CRUD__SCHEMA
Value: 
•	Name: EXPERIENCIA_LABORAL_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe 
eventos_crud

•	Name: API_EVENTOS_HTTP_PORT
Value: 8081
•	Name: EVENTOS_CRUD__PGUSER
Value: 
•	Name: EVENTOS_CRUD__PGPASS
Value: 
•	Name: EVENTOS_CRUD__PGURLS
Value: 
•	Name: EVENTOS_CRUD__PGDB
Value: 
•	Name: EVENTOS_CRUD__SCHEMA
Value:
•	Name: EVENTOS_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
evaluacion_inscripcion_crud

•	Name: EVALUACION_INSCRIPCION_HTTP_PORT
Value: 9016
•	Name: EVALUACION_INSCRIPCION_CRUD__PGUSER
Value: 
•	Name: EVALUACION_INSCRIPCION_CRUD__PGPASS
Value:
•	Name: EVALUACION_INSCRIPCION_CRUD__PGURLS
Value:
•	Name: EVALUACION_INSCRIPCION_CRUD__PGDB
Value: 
•	Name: EVALUACION_INSCRIPCION_CRUD__SCHEMA
Value: 
•	Name: EVALUACION_INSCRIPCION_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
ente_crud

•	Name: ENTE_HTTP_PORT
Value: 8096
•	Name: ENTE_CRUD__PGUSER
Value: 
•	Name: ENTE_CRUD__PGPASS
Value: 
•	Name: ENTE_CRUD__PGURLS
Value: 
•	Name: ENTE_CRUD__PGDB
Value: 
•	Name: ENTE_CRUD__SCHEMA
Value: 
•	Name: ENTE_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
documentos_crud

•	Name: DOCUMENTOS_HTTP_PORT
Value: 8094
•	Name: DOCUMENTOS_CRUD__PGUSER
Value: 
•	Name: DOCUMENTOS_CRUD__PGPASS
Value: 
•	Name: DOCUMENTOS_CRUD__PGURLS
Value: 
•	Name: DOCUMENTOS_CRUD__PGDB
Value: 
•	Name: DOCUMENTOS_CRUD__SCHEMA
Value: 
•	Name: DOCUMENTOS_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
documento_programa_crud

•	Name: DOCUMENTO_PROGRAMA_HTTP_PORT
Value: 9014
•	Name: DOCUMENTO_PROGRAMA_CRUD__PGUSER
Value:
•	Name: DOCUMENTO_PROGRAMA_CRUD__PGPASS
Value: 
•	Name: DOCUMENTO_PROGRAMA_CRUD__PGURLS
Value:
•	Name: DOCUMENTO_PROGRAMA_CRUD__PGDB
Value: 
•	Name: DOCUMENTO_PROGRAMA_CRUD__SCHEMA
Value: 
•	Name: DOCUMENTO_PROGRAMA_CRUD__LOG
Value:
•	Name: DOCUMENTO_PROGRAMA_CRUD__PGDB_MIGRATION
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
descuento_academico_crud

•	Name: DESCUENTO_ACADEMICO_CRUD_HTTP_PORT
Value: 9013
•	Name: DESCUENTO_ACADEMICO_CRUD__PGUSER
Value:
•	Name: DESCUENTO_ACADEMICO_CRUD__PGPASS
Value:
•	Name: DESCUENTO_ACADEMICO_CRUD__PGURLS
Value:
•	Name: DESCUENTO_ACADEMICO_CRUD__PGDB
Value:
•	Name: DESCUENTO_ACADEMICO_CRUD__SCHEMA
Value:
•	Name: DESCUENTO_ACADEMICO_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
core_crud

•	Name: CORE_CRUD_HTTP_PORT
Value: 8102
•	Name: CORE_CRUD__PGUSER
Value:
•	Name: CORE_CRUD__PGPASS
Value:
•	Name: CORE_CRUD__PGURLS
Value: 
•	Name: CORE_CRUD__PGDB
Value: 
•	Name: CORE_CRUD__SCHEMA
Value: 
•	Name: CORE_CRUD__LOG
Value:

**Comment by jevilla94** [comment]
@BOTOOM @miguerpe @neconoe
campus_mid

•	Name: CAMPUS_MID_HTTP_PORT
Value: 8095
•	Name: CAMPUS_MID_LOG
Value:
•	Name: ENTE_SERVICE
Value: (ruta ente_crud)
•	Name: PERSONAS_SERVICE
Value: (ruta personas_crud)
•	Name: ORGANIZACION_SERVICE
Value: (ruta organizacion_crud)
•	Name: UBICACIONES_SERVICE
Value: (ruta ubicaciones_crud)
•	Name: FORMACION_ACADEMICA_SERVICE
Value: (ruta formacion_academica_crud)
•	Name: EXPERIENCIA_LABORAL_SERVICE
Value: (ruta experiencia_laboral_crud)
•	Name: PROGRAMA_ACADEMICO_SERVICE
Value (ruta programa_academico_crud)
•	Name: PRODUCCION_ACADEMICA_SERVICE
Value: (ruta produccion_academica_crud)
•	Name: DESCUENTO_ACADEMICO_SERVICE
Value: (ruta descuento_academico_crud)
•	Name: INSCRIPCION_SERVICE
Value: (ruta inscripcion_crud )
•	Name: EVALUACION_INSCRIPCION_SERVICE
Value: (ruta evaluacion_inscripcion_crud)

**Comment by BOTOOM** [comment]
@jevilla94 muchas gracias

**Comment by BOTOOM** [comment]
@jevilla94 hay un pequeño dato que ustedes si pueden proporcionar y es el esquema que usan las apis ya que el backup es tal cual como ustedes nos lo pasaron

**Comment by BOTOOM** [comment]
@jevilla94 @miguerpe @neconoe , porfavor indicarme los esquemas que usa cada api ya que estoy realizando solicitudes para los usuarios de las apis y que tengan acceso a la base de datos, pero cada api tiene su propio usuario y cada usuario solo debe de tener los esquemas que toca el api, por favor colaborarme con esto
