### ISSUE TITLE
analizar funcionaidad de compomiso apis de fianciera

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/financiera_documentacion#182]
se requiere analizar principalmente las apis de :
- [api_financiera](https://github.com/udistrital/api_financiera)
- [api_mid_financiera](https://github.com/udistrital/api_mid_financiera)

***( Nota si se encuentra algo relevante en algún repo informar el repo)**

con la finalidad de encontrar que se encuentra de compromisos allí para ello se recomienda.

- [x] analizar código y reconstruir el modelo de datos.

- [x] revisar la lógica y funciones utilizadas

- [x] que apis consumen en las funciones utilizadas

**Comment by Jeisson005** [comment]
# api_financiera (Compromiso)
## Modelo de datos
El modelo encontrado en la documentación en su última versión es el siguiente:
[modelov3.png]
https://drive.google.com/file/d/0BzMLsZbBoQNeR095TUlxdXB4SjQ/view?usp=sharing

El siguiente es el modelo reconstruido a partir del _api_financiera_, éste solo incluye las tablas relacionadas con _Compromiso_.
![compromiso](https://user-images.githubusercontent.com/24659130/104770298-5d4f5080-573e-11eb-89a2-d571d4d07544.png)

El siguiente es el archivo del modelo, el cual fue creado en _pgmodeler_
https://drive.google.com/file/d/1J0gu5I2cIkJlk3_nJWJbL5g36jCEVY_W/view?usp=sharing

## Rutas, controladores y modelos
Las siguientes son las rutas, controladores y modelos que se relacionan con _compromisos_
|Ruta|Controlador|Modelo|
|-------------------------------------------------|-------------------------------------------------------|-------------------------------------------------------|
|     /categoria_compromiso                   |        CategoriaCompromisoController   |  CategoriaCompromiso |
|     /tipo_compromiso_tesoral                   |        TipoCompromisoTesoralController       | TipoCompromisoTesoral|
|     /estado_compromiso                   |        EstadoCompromisoController       | EstadoCompromiso|
|     /compromiso                   |        CompromisoController       | Compromiso|

## Funciones
Todos los controladores cuentan con las funciones **Post, GetOne, GetAll, Put** y **Delete**

# api_mid_financiera (Compromiso)
## Modelos
Se encuentran 4 modelos directamente relacionado con compromisos que son los siguientes:
- CategoriaCompromiso
- TipoCompromisoTesoral
- EstadoCompromiso
- Compromiso
Los modelos en su mayoría se encuentran iguales o con algunos campos menos respecto al modelo reconstruido.
Sin embargo, hay una variación en el modelo _TipoCompromisoTesoral_ ya que éste no cuenta con el campo **"activo"**, el cual fue reemplazado por el campo **"estado_activo"**

## Funciones
También se encuentra el uso de compromisos en las funciones **formatoSolicitudRP** y **GetSolicitudesRpByID** en el controlador del archivo _registropresupuestal.go_; en ambas funciones se realiza una conexión con el _api_financiera_crud_ para cargar los datos del compromiso correspondientes a la solicitud de registro presupuestal.

## APIs que se consumen
El api_mid_financiera en relación a compromisos solo hace uso del endpoint **/compromiso** del _api_financiera_crud_.

# Otras APIs
## plan_cuentas_mid
El modelo de SolicitudCrp se relaciona mediante una llave foranea con Compromiso
## presupuesto_mid
Se encuentra un modelo de compromiso igual al del modelo reconstruido
##
