### ISSUE TITLE
analizar funcionalidad de avances apis de financiera

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/financiera_documentacion#183]
se requiere analizar principalmente las apis de :
- [api_financiera](https://github.com/udistrital/api_financiera)
- [api_mid_financiera](https://github.com/udistrital/api_mid_financiera)

***( Nota si se encuentra algo relevante en algún repo informar el repo)**

con la finalidad de encontrar que se encuentra de avances allí para ello se recomienda.

- [x] analizar código y reconstruir el modelo de datos.

- [x] revisar la lógica y funciones utilizadas

- [x] que apis consumen en las funciones utilizadas

**Comment by NRDaza** [comment]
# api_financiera(Tema avances)

## Modelo de datos
El modelo solo incluye las tablas relacionadas con `Avance `, las tablas de `rubro`. `cuenta especial`, `orden de pago`, etc. Se agregan debido a que hacen parte de alguna tabla de avance, sin embargo si estas tablas incluyen llaves foraneas de otras tablas no se agregaron para no extender el modelo.
![Modelo_datos_Avance_Api_financiera-2021-01-14_09-47](https://user-images.githubusercontent.com/34488581/104606253-87751580-564d-11eb-8053-416bdeb8f056.png)

### Enlace archivo XML
https://drive.google.com/file/d/1kYBE2vAChKHe18rN1MG_NXJTkfosKA21/view?usp=sharing

## Rutas y controladores relacionados con avances

|     Rutas                                       |     Controladores                                     |
|-------------------------------------------------|-------------------------------------------------------|
|     /tipo_avance_legalizacion                   |     TipoAvanceLEgaliacionController                   |
|     /**avance_legalizacion**                        |     **AvanceLegalizacionController**                      |
|     /avance_legalizacion_cuenta_especial        |     AvanceLegalizionCunetaEspecialController          |
|     /etapa_avance                               |     EtapaAvanceController                             |
|     /requisito_avance                           |     RequisitoAvanceController                         |
|     /presupesto_avance                          |     PresupuestoAvanceControlelr                       |
|     /avance_estado_avance                       |     AvanceEstadoAvanceController                      |
|     /estado_avance                              |     EstadoAvanceController                            |
|     /solicitud_avance                           |     SolicitudAvanceController                         |
|     /tipo_avance                                |     TipoAvanceController                              |
|     **/solicitud_tipo_avance**                      |     **SolicitudTipoAvanceController**                     |
|     /requisto_tipo_avance                       |     RequisitoTipoAvanceController                     |
|     **/solicitud_requistio_tipo_avance**            |     **SolicitudRequistoTipoAvanceController**             |
|     **/reintegro_avance_legalizacion**              |     **ReintegroAvanceLegalizacionController**             |
|     **/orden_pago_avance_legalizacion**             |     **OrdenPagoAvanceLegalizacionController**             |
|     **/avance_legalizacion_tipo**                   |     **AvanceLegalizacionTipoController**                  |
|     **/concepto_avance_legalizacion_tipo**          |     **ConceptoAvanceLegalizacionTipoController**          |
|     **/estado_legalizacion_avance_legalizacion**    |     **EstadoLegalizacionAvanceLegalizacionController**    |
|     /avance_legalizacion_sub_tipo               |     AvanceLEgalizacionSubTipoController               |
|     /estado_avance_legalizacion_tipo            |     EstadoAvanceLegalizacionTipoController            |

## Funciones
Todos contienen solo funciones POST, GETONE, GETALL, PUT, DELETE, Los elementos en negrilla contienen las siguientes funciones adicionales:

**AvanceLegalizacionController:**

- `GetLegalizacionRecordsNumber()` : `router /GetLegalizacionRecordsNumber/ [get]` , Trae la cantidad/número de registros en la tabla de `avance_legalizacion`.

**SolicitudAvanceController:**

- `TrSolicitudAvance()`:` router TrSolicitudAvance/ [post]`, Crear solicitud de avance.
- `GetRecordsNumberSolicitudAvance()` : `router / GetSolicitudesNumber/ [get]` , Trae la cantidad/número de registros en la tabla de `solicitud_avance`.

**SolicitudRequisitoTipoAvanceController:**

- `TrValidarAvance( )`: `router TrValidarAvance/ [post]` , Validar Avance de una solicitud.

**ReintegroAvanceLegalizacionController:**

- `AddReintegroAvance()`: `router /AddReintegroAvance [post]` , Inserta un nuevo registro a la tabla `reintegro_avance_legalizacion` y regresa el Id del registro.

**OrdenPagoAvanceLegalizacionController:**

- `AddOPAvance()`:` router /AddOPAvance [post]` , Inserta multiples datoas a la tabla  `orden_pago_avance_legalizacion`.

**AvanceLegalizacionTipoController:**

- `AddEntireAvanceLegalizacionTipo()` :` router /AddEntireAvanceLegalizacionTipo [post]`,  Valida que la suma  del `valorLegalizadoAvance `y `valor `sea menor que el `valorTotalAvance`, si es menor inserta un nuevo  registro a la tabla `avance_legalizacion_tipo`.
- `GetLegalizationValue()`:` router /GetLegalizationValue/:id [get]`, obtiene la suma de todos los pagos por adelantado de legalización, incluidos los reembolsos.
- `GetTaxesMovsLegalization()` :  `router /GetTaxesMovsLegalization [get]` , Obtener impuestos para un tipo de legalización dado una `Id`.
- `PutAllAvanceLeg()`:` router / [put]` ,  Actualiza la información de la tabla `avance_legalizacion_tipo`.

**ConceptoAvanceLegalizacionTipoController:**

- `GetConceptoAvanceLegalizacionId() `: `router /GetConceptoAvanceLegalizacionId/:id [get]` , Retorna un  `ConceptoAvanceLegalizacionTipo `dado `IdAvanceLegalizacion`

**EstadoLegalizacionAvanceLegalizacionController:**

- `AddEstadoLegalizacion()` : `router /AddEstadoLegalizacion [post]` , Insertar un registro para modificar el estado de una legalización


# api_financiera_mid(tema avances)

Solo se encuentra 4 archivos relacionados con avance `avance.go`, `legalización_avance.go`, `CommentsRoutes`, `Router`

## Rutas y controladores relacionados con avances

|     Rutas                   |     Controladores                   |
|-----------------------------|-------------------------------------|
|     /legalización_avance    |     LegalizacionAvanceController    |
|     /Avance                 |     AvanceController                |

## Funciones

### **AvanceController():** 

**GetAvanceById()**: Construye una solicitud de avance con los siguientes ENDPOINTs

- **ENDPOINT** : `Api_Financiera_Crud /solicitud_avance/:id`
- **ENDPOINT** : `Api_Financiera_Crud /solicitud_tipo_avance/?query=SolicitudAvance.Id:"+idStr`
- **ENDPOINT** : `Api_Financiera_Crud /avance_legalizacion_tipo/GetLegalizationValue/"+idAvceLeg`
- **ENDPOINT** : `http://10.20.0.127/urano/index.php...` **[ Traer info de Beneficiario]**

**getTiposInfo()**: Usada en `GetAvanceById `para completar la solicitud de tipo de avance

- **ENDPOINT** : `Api_Financiera_Crud/requisito_tipo_avance/?query=TipoAvance:"+tipoId+",Activo:1&limit=-1&fields:RequisitoAvance,TipoAvance,Id&sortby=TipoAvance&order=asc`

**GetSolicitudes()** : Regresa el avance las solicitudes

- **ENDPOINT** : `Api_Financiera_Crud /solicitud_avance/`
- **ENDPOINT** : `Api_Financiera_Crud /solicitud_avance/GetSolicitudesNumber/ `**[Cuantas solicitudes hay]**

**getSolicitudInfo()**: Usada en `GetSolicitudes `para completar la solicitud

- **ENDPOINT** : A`pi_Financiera_Crud /avance_estado_avance/?query=SolicitudAvance.Id:"+solicitudId+"&limit=-1&sortby=FechaRegistro&order=desc` **[Consulta estados de la solicitud]**
- **ENDPOINT** :` servicios_academicos/consulta_datos_docente_planta/+ beneficiarioID` **[retorna información beneficiario]**
- **ENDPOINT** : `Api_Financiera_Crud /solicitud_tipo_avance/?query=SolicitudAvance.Id:"+solicitudId+"&limit=-1&sortby=Id&order=asc`
- **ENDPOINT** : `Api_Financiera_Crud/requisito_tipo_avance/?query=TipoAvance:"+strIdTipoAvc+",Activo:1&fields=RequisitoAvance,TipoAvance,Id&limit=-1&sortby=TipoAvance&order=asc `**[Por cada tipo revisa este endpoint]**


### **LegalizacionAvanceController():**

**GetAllLegalizacionTipo()** : Retorna todas los datos de la tabla AvanceLegalizacionTipo.

- **ENDPOINT** : `Api_Financiera_Crud /avance_legalizacion_tipo/ `


**formatoLegalizacion()** : Usada en `GetAllLegalizacionTipo()`, valida si el tipo de legalización es Compra,Practica academica u otra usando la función `formatoLegalizacionDispatcher()` , dependiendo de la legalización realiza una consulta diferente a `getLegalizacionCompra()` o  `getLegalizacionPracticaAcadem() `

- **ENDPOINT** : `Api_Financiera_Crud /concepto_avance_legalizacion_tipo/?query=AvanceLegalizacion.Id:idAvaLeg` **[idAvaLeg  depende de la legalización ]**


**formatoLegalizacionDispatcher()**: Valida según el tipo de legalización que consulta hacer se tiene caso 1 (`getLegalizacionPracticaAcadem()`), caso 2 `(getLegalizacionCompra()`)o el caso por defecto retorna `nil`


**getLegalizacionCompra()** : Construye información del proveedor, según el provedor se realiza un consulta a un ENDPOINT diferente

- **ENDPOINT** : `AdministrativaAmazonService/informacion_proveedor/`
- **ENDPOINT** : `AdministrativaAmazonService/ informacion_persona_natural/`
- **ENDPOINT** : `AdministrativaAmazonService/ parametro_estandar/`
- **ENDPOINT** : `AdministrativaAmazonService/ parametro_estandar/11`



**getLegalizacionPracticaAcadem()**: Consulta información del estudiante

- **ENDPOINT** :  `Wso2Service/bienestarProxy/info_basica/`


**GetLegalizacionInformation()**: Trae información de una legalización según el `Id `del avance

- **ENDPOINT** : `Api_Financiera_Crud /avance_legalizacion//?query=Avance.Id:Id`
- **ENDPOINT** : `Api_Financiera_Crud /avance_legalizacion_tipo/GetLegalizationValue/` **[Ver valor de la legalización]**

**GetAllLegalizacionAvance()** : Retorna los avances de legalización y la cantidad de registros  existentes.  además, usa la función `getValuesLegalizacion()` para traer el estado y el valor de la legalización .

- **ENDPOINT** : `Api_Financiera_Crud /avance_legalizacion`
- **ENDPOINT** :  `Api_Financiera_Crud /avance_legalizacion/GetLegalizacionRecordsNumber/`

**getValuesLegalizacion()**: Revisar estado y valor de la legalización.

- **ENDPOINT** : `Api_Financiera_Crud /estado_legalizacion_avance_legalizacion/?query=Activo:true,AvanceLegalizacion.Id:Id`
- **ENDPOINT** :  `Api_Financiera_Crud / avance_legalizacion_tipo/GetLegalizationValue/:Id`

**GetLegalizacionAccountantInformation()** : Obtener información contable para una legalización usa la función `getAccountantInfoLeg()` para realizar un complemento a la información contable.

- **ENDPOINT** :` Api_Financiera_Crud /avance_legalizacion_tipo/?query=AvanceLegalizacion.Id:idAvceLeg,EstadoAvanceLegalizacionTipo.Id:1`
- **ENDPOINT** :  `Api_Financiera_Crud /concepto_avance_legalizacion_tipo/GetConceptoAvanceLegalizacionId/+idAvceLeg`

**getAccountantInfoLeg()**: Revisa el concepto de una legalización y el movimiento contable según el concepto, el documento del afectante y tipo de legalización 

- **ENDPOINT** : `Api_Financiera_Crud /concepto_avance_legalizacion_tipo/?query=AvanceLegalizacion.Id:idLegTipo`
- **ENDPOINT** :  `Api_Financiera_Crud/movimiento_contable/?query=Concepto.Id:conceptoID,CodigoDocumentoAfectante:idLegTipo,TipoDocumentoAfectante.Id:idTipoDocAfectante&fields=Id,Credito,Debito,CuentaContable,Concepto`
