### ISSUE TITLE
analizar funcionalidad de giros apis de financiera

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/financiera_documentacion#184]
se requiere analizar principalmente las apis de :
- [api_financiera](https://github.com/udistrital/api_financiera)
- [api_mid_financiera](https://github.com/udistrital/api_mid_financiera)

***( Nota si se encuentra algo relevante en algún repo informar el repo)**

con la finalidad de encontrar que se encuentra de giros allí para ello se recomienda.

- [x] analizar código y reconstruir el modelo de datos.

- [x] revisar la lógica y funciones utilizadas

- [x] que apis consumen en las funciones utilizadas

**Comment by Miranda13** [comment]
# Api_financiera 

## Rutas y controladores relacionados con giros

Rutas | Controladores
------------ | -------------
giro | GiroController
giro_estado_giro | GiroEstadoGiroController
giro_detalle | GiroDetalleController
estado_giro | EstadoGiroController

## Funciones 

Cada uno de los controladores mostrados en la anterior tabla tienen las funciones: POST, GETONE, GETALL, PUT, DELETE. Únicamente *GiroController* tiene funciones adicionales se listan a continuación:

*GiroController:*

- `RegistrarGiro()` : Registra los giros de órdenes de pago de proveedores, concepto de orden de pago y movimientos contables. 
- `GetCuentasEspeciales()` : Con el Id de orden de pago se obtienen las cuentas especiales. 
- `GetSumGiro()` : Obtiene la suma del giro. 
- `GetValueEndoso()` : Obtiene el valor del endoso con el id de orden de pago y el id de cuenta especial.
- `RegistrarGiroDescuentos()` : Registra descuentos a partir de el `idGiro`, `idCuenta`, `idOrdenPago` y `resProveedor`.
