### ISSUE TITLE
Socialización generación de consecutivos respecto a las necesidades, CDP y CRP

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_documentacion#19]
EN el Issue se toman en cuenta los siguientes temas:
- Socialización flujo de una necesidad, solicitud de CDP, CDP, solicitud de CRP, CRP 

- Socialización generación de consecutivos respecto a las necesidades, CDP y CRP

**Comment by mcrubianot** [comment]
Teniendo en cuenta que es necesario tener claros algunos conceptos necesarios dentro de los desarrollos, se programó sesión de trabajo el día 10 de septiembre del año en curso, con la asistencia del líder del proyecto, líder técnico y desarrolladores.

De la misma forma se dió una revisión al flujo de proceso desde las necesidades hasta la generación del CRP.

Se anexa el documento que se utilizó en dicha reunión.

https://docs.google.com/document/d/1gdjXbSNkTCjDvij826z6Y9nTg51-QMuuD9l06U0EzEk/edit

**Comment by Soulfilip-UD** [comment]
La socialización se realizo y se resolvieron las dudas, se tomaron los apuntes correspondientes. Se finaliza la tarea 

Proceeding to close Issue 👾
