### ISSUE TITLE
Informe de análisis Subsistema de Contabilidad

### ISSUE THREAD

**Issue by macaguegi** [udistrital/Financiera_documentacion#2]
Se solicita : 

- [x] Crear un informe escrito :page_facing_up:  analizando las funcionalidades del Susbsistema de Contabilidad en el ambiente de pruebas del Sistema Financiero KRONOS

**Comment by macaguegi** [comment]
Se realiza análisis del módulo "Gestión del Plan de Cuentas" y se adjunta enlace a documento 
[Informe](https://docs.google.com/document/d/1TDl__7y2Ss1QVWndXYEdDwhto3UZ9CK5xvFssFVI6m0/edit?usp=sharing)

Queda pendiente realizar revisión y análisis de Comprobantes.

**Comment by macaguegi** [comment]
Se hace revisión de la Gestión de Comprobantes . Documento disponible en
[Documento](https://docs.google.com/document/d/1TDl__7y2Ss1QVWndXYEdDwhto3UZ9CK5xvFssFVI6m0/edit?usp=sharing)

**Comment by Soulfilip-UD** [comment]
Se anexan concusiones y la lider de proyecto estara entregando un feedbak  de este.
[Análisis de Subsistema de Contabilidad.pdf](https://github.com/udistrital/Financiera_documentacion/files/3383281/Analisis.de.Subsistema.de.Contabilidad.pdf)

Tarea finalizada
Proceeding to close Issue :space_invader:
