### ISSUE TITLE
informe con diagrama y proceso de datos que se consume para Certificados de Retenciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/financiera_documentacion#205]
se requiere realizar un informe el cual contenga diagramas de los datos a usar y del proceso de consumo de esos datos, para el proceso de consumo de satos se da sugerencia de un diagrama de secuencia, estas tareas con la finalidad de dar un primer acercamiento a los recursos y procesos que se han de necesitar para realizar el respectivo informe, para ello se proporcionan los siguientes documentos

- [Documento de nalisis](https://docs.google.com/document/d/1yLp1eNfeNJO-sRNBAZiGBKhJZOPeO6DmTqm5gpwmeqM/edit)
- [procedimiento Sigud](http://sigud.udistrital.edu.co/vision/filesSIGUD/SIGUD%202018/Gestion%20de%20Recursos%20Financieros/GRF-PR-025/#list)

***Nota: el informe no se es necesario en ningún documento, realice el informe en los comentarios del presente issue***

**Comment by criss201x** [comment]
# Informe de análisis del proceso GRF-PR-025 - Certificado de Retenciones

El presente informe tiene como objetivo ilustrar el flujo de datos en el proceso [GRF-PR-025 - Certificado de Retenciones](http://sigud.udistrital.edu.co/vision/filesSIGUD/SIGUD%202018/Gestion%20de%20Recursos%20Financieros/GRF-PR-025/#diagram/1766c20b-ffc5-46cf-bce7-75c1365d17b2) identificando el origen de los datos y el proceso de consumo de los mismos. 

## Diagrama de origen de los datos 

El siguiente diagrama corresponde a la notación UML del diagrama de despliegue cuya finalidad es modelar la disposición de los artefactos de software a nivel físico o de hardware. En este caso se hace uso de este diagrama para representar los diferentes documentos, formatos, reportes, entre otros, que involucran datos e información relevante durante el proceso GRF-PR-025. Adicionalmente, se refleja el origen de dichos artefactos y sus relaciones de dependencia.

![Diagrama de Despliegue - GRF-PR-025 - CERTIFICADOS DE RETENCIONES](https://user-images.githubusercontent.com/57843585/106290560-9c8aa080-6218-11eb-9895-56418e5e78f0.png)

**NOTA:** si desea consultar la definición de cada elemento del diagrama de despliegue diríjase al siguiente [enlace](https://www.lucidchart.com/pages/es/tutorial-de-diagramas-de-despliegue) 

### Observaciones 

- El reporte de retenciones obtenido a través de SIIGO parte de una previa consolidación del proceso [GRF-PR-022, INFORMACIÓN EXÓGENA](http://sigud.udistrital.edu.co/vision/filesSIGUD/SIGUD%202018/Gestion%20de%20Recursos%20Financieros/GRF-PR-022/#diagram/1766c20b-ffc5-46cf-bce7-75c1365d17b2)
- El reporte de recursos humanos aplica para administrativos, docentes y docentes de hora cátedra
- Se identifica que en el caso de que existan certificados para funcionarios (personas naturales) que hayan sido generados previamente, estos pueden ser descargados a través del Sistema de Gestión Académica. En el caso de los certificados nuevos o de personas jurídicas estos son generados a través del sistema SIIGO
- Se desconocen los formatos de los documentos asociados a el Reporte de recursos humanos, Reporte de pagos por fuera de nómina, Reporte de retenciones consolidado, Reporte de novedades, Documentos de pago y movimientos contables del tercero, así como los formatos de órdenes de pago

## Proceso de consumo de datos 

Para identificar el proceso de consumo de datos dentro de las actividades relacionadas con el proceso GRF-PR-025 - Certificado de Retenciones, se propone el uso de un diagrama de secuencia el cual refleja los actores, sistemas y dependencias involucrados desde la fase de Generación hasta la fase de Expedición del certificado de retenciones. De igual manera, se destacan las operaciones de comunicación entre los participantes, así como el flujo y transformación de la información.

![Diagrama de Secuencia - GRF-PR-025 - CERTIFICADOS DE RETENCIONES](https://user-images.githubusercontent.com/57843585/106295438-70721e00-621e-11eb-8d26-d9cb19cb50a9.png)

**NOTA:** si desea consultar la definición de cada elemento del diagrama de secuencia diríjase al siguiente [enlace](https://www.lucidchart.com/pages/es/diagrama-de-secuencia) 
 
 ### Observaciones 

- Se desconoce sobre las funciones de la Sección de Novedades
- Es importante considerar si el reporte de pagos y el reporte de novedades se deben generar con una herramienta de software  
- Se desconoce el formato de la solicitud que realiza el tercero para la expedición del certificado de retenciones 
- El proceso para la generación de certificados de retenciones para personas jurídicas y personas naturales es diferente. El formato del documento generado en cada caso también presenta diferencias. Adicionalmente, la fuente del certificado cambia si se expide un certificado para un funcionario, el cual haya sido generado con anterioridad 
---
_Elaborado por: Cristian Alape(@criss201x) y Jonathan Capera(@JocoolQ)_
