### ISSUE TITLE
Aprobación y seguimiento del modelo de datos Fuentes de financiamiento y productos - 3 hora - Arquitectos, DBA , Felipe , Miguel, David, Juan Camilo

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#21]
Leyendo las historias de usuario y revisando los mockups, se levantan los modelos de datos para items: fuentes de financiamiento y productos.

Los cuales se realizaron con colecciones de mongo.

**Comment by jairolh** [comment]
Se válida modelos de datos

**Comment by nodier25** [comment]
Se válida modelo para bases de datos

**Comment by Soulfilip-UD** [comment]
Gracias, viendo que no se necesitan ajustes se cerrara el Issue

Proceeding to close Issue 👾

**Comment by Soulfilip-UD** [comment]
Se anexan los cambios en el [Issue](https://github.com/udistrital/plan_cuentas_mongo_crud/issues/89)
