### ISSUE TITLE
Socialización mockups de fuentes y productos - 1 hora

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#23]
Revisar con la analista los mockups de fuentes y productos.

- [ ] Anexar todos los issue o mockups al Issue
- [ ] Plantear reunión para la revisión

**Comment by mcrubianot** [comment]
Se revisan los mockups planteados en la siguiente dirección.
https://drive.google.com/file/d/15NPQQImfPr2EmWjsuWwMynRwZYbm4Oqn/view

Se observa de mi parte lo siguiente. Si bien es cierto que una modificación requiere una solicitud, no aplica para que se haga la solicitud en el sistema, toda vez que esto viene directamente aprobado por la SHD y ellos no interoperarían con el sistema.

Otra cosa es que Kronos (Sección de Presupuesto) registre en el sistema la modificación y eso afecte la apropiación inicial y ya.

**Comment by Soulfilip-UD** [comment]
Se plantea realizar una socialización el día de mañana(17 de Septiembre) a las 2 pm, para los mockups de fuentes y productos.

**Comment by mcrubianot** [comment]
Se hace la respectiva socialización y se revisan los mockups.

Se validan de acuerdo a lo presentado.

**Comment by Soulfilip-UD** [comment]
Observaciones a tener en cuenta respecto a Fuentes:

- [ ] Solo a los rubros de las apropiaciones de ingresos es a los que se les puede asociar una fuente de financiamiento

- [ ] Todos los rubros de apropiaciones de ingresos deben tener asociada una fuente

- [ ] El proceso para registrar conlleva los pasos previos: 
---> Se empieza a construir las preapropiaciones para la vigencia 2020 para validarlo con hacienda
---> En caso de que hacienda no lo apruebe deben modificar la preapropiación hasta que la apruebe
---> Cuando la aprueba hacienda me anexa las fuentes y los rubros asociados a la fuente, asimismo hacienda me está anexando los productos asociados a los rubros y el %, se aprueba las apropiaciones para 2020 en el sistema
---> Planeación es quien decide que dependencias aplican al rubro, solo aplica para inversión
---> Planeación le asigna el valor por depencia sobre el valor total de la apropiación 
 
- [ ] A los rubros de financiación no se les asigna dependencia ya que es general

- [ ] No pueden haber movimientos entre rubros de financiamiento y rubros de inversión

- [ ] Queda la duda... el valor designado a una dependencia es modificacble? hasta donde se entiende no es modificable

- [ ] No hay movimientos entre dependencias

- [ ] El control de presupuesto vs gasto se da sobre el seguimiento de movimientos de CDP, CRP, Ordenes, giros

Observaciones respecto a productos:

- [ ] El producto es un objeto misional, en un informe es la bandera que indica cuanto se invirtio en un campo 

- [ ] Hacienda asocia los rubros a las apropiaciones bajo porcentajes % de números enteros

- [ ] Solo los rubros de apropiaciones pueden tener productos asociados

- [ ]  Cuando a un rubro se le asigna uno o mas productos el porcentaje total siempre debe ser 100%

- [ ] Cuando se modifica el valor de un rubro , se automodifica el valor del producto sobre el rubro, se mantiene como un porcentaje.



Como Dato general, presupuesto tiende a hacer una modificación sobre el rubro y después sobre la fuente.

**Comment by mcrubianot** [comment]
Ingenieros hago una observación respecto a lo relacionado en la nota anterior.

 **"Solo a los rubros de las apropiaciones de ingresos es a los que se les puede asociar una fuente de financiamiento"**

La fuente hasta donde conozco y el analisis que se ha hecho vienen asociadas a los rubros del GASTO no del INGRESO



**"Queda la duda... el valor designado a una dependencia es modificacable? hasta donde se entiende no es modificable".**

El valor asignado a una dependencia si es modificable. De acuerdo con los movimientos presupuestales se modifica un rubro, me modifican las fuentes y se modifican los valores de las dependencias.

 **Todos los rubros de apropiaciones de ingresos deben tener asociada una fuente**

LoS rubros del GASTO

 **A los rubros de financiación no se les asigna dependencia ya que es general**

Por favor tener cuidado con los términos, son rubros de FUNCIONAMIENTO, NO FINANCIACION, son dos cosas totalmente diferentes.

**El control de presupuesto vs gasto se da sobre el seguimiento de movimientos de CDP, CRP, Ordenes, giros**

Considero que sobra el **vs** ya que el presupuesto de gastos de ejecuta mediante los diferentes movimientos que se dan sobre CDP, CRP, Ordenes, giros
 
 **Hacienda asocia los rubros a las apropiaciones bajo porcentajes % de números enteros**

... Asocia los rubros ?...... no asocia los productos

**Cuando a un rubro se le asigna uno o mas productos el porcentaje total siempre debe ser 100%**

Recuerden que esto debe ser muy bien analizado por que no puede ser 99.99999999% debe ser siempre 100%

**Comment by Soulfilip-UD** [comment]
Datos corregidos

**Comment by Soulfilip-UD** [comment]
No se pudo realizar la socialización en la semana, por lo que queda planeada revisarlos el lunes 7 de Octubre

**Comment by Soulfilip-UD** [comment]
Actualmente se está realizando la validación del sistema, por lo que el tiempo sera dedicado a pulir el desarrollo en test 

Proceeding to close Issue 👾
