### ISSUE TITLE
Socialización de modelo de datos de CDP y CRP , con arquitectos y DBA

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#24]
Se requiere contar con los arquitectos y dba en este caso para revisar y ajustar en caso dado , los modelos de datos planteados para CDP y CRP, modulos del subsitema de presupuesto.

Documentación del modelo [Modelo de datos CDP y CRP](https://github.com/udistrital/financiera_documentacion/blob/master/plan_cuentas/CDP-CRP/modelo_datos_mongo/ModeloDatos.md)

**Comment by macaguegi** [comment]
Se socializa con arquitectos @corio27 y @jairolh y se hacen las siguientes observaciones : 

- [ ] Se debe agregar la *Vigencia* tanto en el objeto de Solicitud de CDP como en Solicitud de CRP

- [ ] Agregar estado del objeto Solicitud de CDP

- [ ] Adaptarse a los lineamientos de modelos de datos (Activo, Fecha Creación y Fecha Modificación)

**Comment by macaguegi** [comment]
Se hacen las modificaciones solicitadas por arquitectos @corio27 y @jairolh 
**CDP**
```json
{
    "_id": "020201abb243245454554" ,
    "consecutivo": 12, 
    "entidad": 203, 
    "centroGestor": 1 ,
    "necesidad" : 1026, 
    "vigencia": "2019",
    "fechaRegistro": "2018-09-01T05:00:00Z",
    "estado":1,
    "justificacionRechazo" : "" ,
    "infoCdp" : {
        "consecutivo": 12,
        "fechaExpedicion": "2018-09-01T05:00:00Z",
        "estado": 1
    },
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}

``` 
**CRP**
```json
{
    "consecutivo": 10,
    "consecutivoCdp": 11,
    "beneficiario": "1546721254",
    "vigencia": "2019",
    "valor": 5000,
    "compromiso": {
        "numeroCompromiso": 152,
        "tipoCompromiso" : 1
    },
    "infoCrp":{
    	"consecutivo": 100,
    	"fechaExpedicion": "2018-09-01T05:00:00Z",
        "estado": 1
        
    },
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}
```

**Comment by Soulfilip-UD** [comment]
Se corrigieron los siguientes ajustes:

- [ ] Anexar la vigencia al {CDP y CRP} y fechas 

- [ ] Aplicar lineamientos del core {activo , fechaCreación, fechaModificación}

Observaciones:

- [ ] El consecutivo se genera desde el movimiento

- [ ] Los movimientos dan info al CDP para su expedición

**Comment by corio27** [comment]
Ok, sugerencias aplicadas

**Comment by jairolh** [comment]
Verificados ajustes propuestos

**Comment by nodier25** [comment]
Se verifica el modelo de bases de datos y las recomendaciones hechas están ok

**Comment by Soulfilip-UD** [comment]
Gracias , como los ajustes están realizados y todo verifican el modelo de datos finalizare la tarea

Tarea finalizada
Proceeding to close Issue 👾
