### ISSUE TITLE
Socialización de mockups de CDP y CRP - solicitud y expedición

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#25]
Tras haber leído las HU y haber entendido el requerimiento de como un usuario solicita o expide un CDP o CRP se realizaron los respectivos mockups. En los Issues #13 y #15

Por lo que se requiere reunirse con el analista quien conoce del negocio, y revisar si se tienen ajustes sobre estos.

**Comment by Soulfilip-UD** [comment]
Los mockups se encuentran listos para socializar y falta una fecha para reunirse

**Comment by macaguegi** [comment]
Se socializa con analista @mcrubianot y se define el tema de **Tipos de Compromisos** . Por lo cual se hace un ajuste directamente sobre el mockup de Solicitar un CRP donde se deben incluir estos compromisos . [Corrección](https://drive.google.com/file/d/10xroOR9JWO_C-uvoqFlHCttXUw_PP3oJ/view?usp=sharing)

**Comment by mcrubianot** [comment]
Se hace la respectiva reunión y se hacen las siguientes observaciones

- En la expedición del CDP se debe agregar el número de la necesidad
- Tanto en la expedición de CDP como del CRP en la tabla que se muestra, solamente dejar un titulo de Valor en la parte inicial

**Comment by macaguegi** [comment]
> Se hace la respectiva reunión y se hacen las siguientes observaciones
> 
> * En la expedición del CDP se debe agregar el número de la necesidad
> * Tanto en la expedición de CDP como del CRP en la tabla que se muestra, solamente dejar un titulo de Valor en la parte inicial

Se agrega :

- [ ] Valores monetarios deberían visualizarse a la derecha

- [ ] Se debe agregar el mockup de expedición de documento CRP

**Comment by Soulfilip-UD** [comment]
Se anexa la carpeta gestion_egresos y se anexa la documentación de CDP/CRP a está.
El nuevo [link de la documentación](https://github.com/udistrital/financiera_documentacion/blob/master/gestion_egresos/CDP-CRP/mockups.md)

**Comment by mcrubianot** [comment]
Se realizan las revisiones solicitadas por el ingeniero Felipe. 

https://drive.google.com/open?id=1EUpPUPn0CwuiQRmJ7rLNOJbwmsADvmnq

**Comment by Soulfilip-UD** [comment]
Se pide revisar de nuevo los mockups por @mcrubianot para confirmar que los ajustes se aplicaron y están aprobados

**Comment by mcrubianot** [comment]
Se hace la revisión del caso 

https://github.com/udistrital/financiera_cliente/issues/597

**Comment by Soulfilip-UD** [comment]
Mockups socializados y finalizados con los ajustes,

Proceeding to close Issue 👾
