### ISSUE TITLE
Socialización de los mockups de movimientos presupuestales con el analista - 1 hora - Maria Claudia, Miguel

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#26]
Tras haber leído las HU y haber entendido el requerimiento de como un usuario realiza un movimiento presupuestal se realizaron los respectivos mockups.

Por lo que se requiere reunirse con el analista quien conoce del negocio, y revisar si se tienen ajustes sobre estos.

**Comment by mcrubianot** [comment]
Se hace una socialización corta de los diferentes tipo de modificaciones presupuestales y se hace un ejemplo práctico de cada uno de ellos.

Se deben hacer algunos ajustes a los mockups.

**Comment by Soulfilip-UD** [comment]
Se tienen las siguientes observaciones:

- [ ] Una resolución (contiene el análisis) es la que permite los movimientos

- [ ] Existe: 
    Cuenta origen   ->  Cuenta credito 
    Cuenta destino -> Cuenta contra-credito

- [ ] En las adiciones siempre ocurren 2 movimientos, uno al rubro de ingreso y otro al rubro de egreso

- [ ] Para hacer una suspensión se hace uso de un CDP, esto ocurre para bloquear el uso de esos fondos en caso de que no se tengan.

- [ ] Asimismo el rubro una vez cuente con los fondos(el dinero de las fuentes), pero no por completo, se puede hacer una suspensión parcial del CDP
___________________________________________________________________________
Asimismo se toca el tema de:

- [ ] Recurso {

- Por el momento no hay un desarrollo de este, se debe revisar en que parte del cronograma se desarrolla

- Se usa para asociar la FF y luego en contabilidad

}
___________________________________________________________________________

- [ ] Tener en cuenta para la nueva revisión de los mockups, la tabla de resumen y el detalle del balance

**Comment by Soulfilip-UD** [comment]
@miguelramirez93 en caso de que los mockups esten finalizados , el jueves 10 de Octubre puedo revisarlos de nuevo con @mcrubianot

**Comment by Soulfilip-UD** [comment]
Mockups Aprobados e Implementados
<img width="947" alt="Screen Shot 2019-12-06 at 12 16 19 AM" src="https://user-images.githubusercontent.com/50924615/70297952-fda61800-17bd-11ea-899e-df78e192595d.png">
<img width="952" alt="Screen Shot 2019-12-06 at 12 16 48 AM" src="https://user-images.githubusercontent.com/50924615/70297953-fda61800-17bd-11ea-87db-65e3af016882.png">
<img width="929" alt="Screen Shot 2019-12-06 at 12 16 57 AM" src="https://user-images.githubusercontent.com/50924615/70297954-fda61800-17bd-11ea-8b1a-409b49d52e46.png">
<img width="937" alt="Screen Shot 2019-12-06 at 12 17 40 AM" src="https://user-images.githubusercontent.com/50924615/70297956-fe3eae80-17bd-11ea-9f03-6eee09e59638.png">
<img width="1066" alt="Screen Shot 2019-12-06 at 12 18 33 AM" src="https://user-images.githubusercontent.com/50924615/70297957-fe3eae80-17bd-11ea-8cf1-c4f260cd5b7e.png">
<img width="580" alt="Screen Shot 2019-12-06 at 12 18 40 AM" src="https://user-images.githubusercontent.com/50924615/70297958-fe3eae80-17bd-11ea-8dc1-5d594d826267.png">

Tarea Finalizada
Proceeding to close Issue 👾
