### ISSUE TITLE
Agregar a los secretos de drone el token y la url de redirect de wso2, para presupuesto y necesidades

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#29]
Para solucionar problemas relacionados a la integración continua se plantea usar los secretos de drone para incluir como variables de entorno absorbidas durante el build de el token adquirido por wso2 al registrar la aplicación y la url de callback también registrada.

Para el cliente de :
- [ ] Necesidades
- [ ] Presupuesto

**Comment by Soulfilip-UD** [comment]
Se ha trabajado en la tarea, se avanzo montando el ambiente de pruebas donde se hace uso de drone localmente y usando todo el pipeline de dockerhub y un repositorio en github, se activa los eventos.

Porcentaje de la tarea 60%

**Comment by Soulfilip-UD** [comment]
Ya se realizaron todas las pruebas sobre el cambio, se está socializando el porque con Fernando Torres ya que es el arquitecto en está sección del pipeline de CI. Una vez aprobado se realizaran los ajustes sobre los repositorios y se agregaran los secretos en el drone que se está usando actualmente.

Tarea en un 80%

**Comment by Soulfilip-UD** [comment]
Tras socializar con Jhon y Fernando , se permitio agregar los secretos , debo enviar el nombre y valor de los secretos a Fernando, para poner a prueba los cambios. Tarea en un 85%

**Comment by Soulfilip-UD** [comment]
Aún no se podido finalizar el desarrollo por prioridad de finalizar con los ajustes del hito 1 de presupuesto, asimismo está semana la prioridad es desplegar los 2 APIs plan_cuentas_mid y movimientos_crud, por lo que se planea realizar la tarea hasta el fin de semana.

**Comment by DianaPatriciaRamirez** [comment]
Es importante mencionar que el hito 1 debió finalizar la etapa de "_Pruebas funcionales de los módulos con el analista de requerimientos_" el 7/Oct/2019, y debido a que a la fecha no se han solucionado las observaciones encontradas por @mcrubianot; es necesario @Soulfilip-UD indicar la razón de atraso de las actividades y del plan de trabajo del proyecto Kronos. 

Por otra parte, se solicita @Soulfilip-UD la fecha de finalización de la presente actividad: "_Agregar a los secretos de drone el token y la url de redirect de wso2, para presupuesto y necesidades #29_"
