### ISSUE TITLE
Creación de Mockup's procesos de Modificaciones Presupuestales para Fuentes de Financiamiento 7 horas  - Carlos

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/financiera_documentacion#3]
- [x] creación mockup adición 
- [x] creación mockup traslado 
- [x] creación mockup reduccion (si aplica)

**Comment by CarlosGutierrezArdila** [comment]
Se dejan los mockups en las pestañas del [Documento](https://drive.google.com/file/d/1nBwIdN-Iue5I164bOOjwuNPBYWJMcBPB/view?usp=sharing) marcadas con modificación, para operaciones de adición, reducción y traslado

**Comment by CarlosGutierrezArdila** [comment]
se actualiza según sugerencias de la anterior semana disponible en documento y repositorio documentación

**Comment by Soulfilip-UD** [comment]
Tarea finalizada , los mockups se encuentran en la siguiente dirección : [Link Imagenes Mockups](https://github.com/udistrital/financiera_documentacion/tree/master/movimientos/movimientos/mockups)

Debo validarlos con Maria C.?

Tarea finalizada
Proceeding to close Issue 👾
