### ISSUE TITLE
Tarjetas en tuleap para - seguridad, Viviana, centro de servicios, y Maria Claudia - Felipe - 1 horas

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#30]
Para la revisión del hito 1 por parte de la oficina hace parte la creación de las tarjetas en tuleap para el area de :

- [ ] Seguridad
- [x] Centro de servicios
- [x] Gestora de comunicaciones
- [x] Asesora del proyecto

**Comment by Soulfilip-UD** [comment]
Se crea la tarjeta para revisar ortografía y redacción: 
-> reuniones #32741
Revisión de hito 1 del sistema de presupuesto (Ortografía y redacción) - Kronos
https://tuleap.udistrital.edu.co/plugins/tracker/?aid=32741

**Comment by Soulfilip-UD** [comment]
En el Issue #12  se lleva la trazabilidad de la socialización con la analista

**Comment by Soulfilip-UD** [comment]
Se crea la tarjeta para la revisión por parte del centro de servicios:

- soporte #32790
Revisión de hito 1 del sistema de presupuesto ( necesidades, rubros presupuestales, apropiaciones iniciales)

**Comment by Soulfilip-UD** [comment]
Se crea la tarjeta para la revisión por parte de seguridad:

- Pruebas #32812
Prueba de seguridad para el desarrollo del proyecto Kronos en su primera entrega
https://tuleap.udistrital.edu.co/plugins/tracker/?aid=32812

**Comment by Soulfilip-UD** [comment]
Tarea realizada en un 100%, queda por seguir las observaciones directamente en las tarjetas o  el Issue

Proceeding to close Issue 👾

**Comment by DianaPatriciaRamirez** [comment]
@Soulfilip-UD Falta indicar la tarjeta tuleap para la revisión funcional por parte de la analista de requerimientos Maria Claudia Rubiano @mcrubianot

**Comment by Soulfilip-UD** [comment]
@DianaPatriciaRamirez La analista no cuenta con un tablero en tuleap, tdas las tareas que le asignamos me dice se llevan seguimiento por github, el issue asociado en el momento es .
recomiendo no cambiar el título del Issue.

> En el Issue #12 se lleva la trazabilidad de la socialización con la analista
