### ISSUE TITLE
Modelo de datos Parametrizar estado de los CDP y CRP , y compromisos

### ISSUE THREAD

**Issue by macaguegi** [udistrital/financiera_documentacion#32]
- [x] Parametrizar y modelar compromisos

⭐️

**Comment by macaguegi** [comment]
Se habla con analista @mcrubianot sobre la existencia de algún documento de análisis donde se puedan contemplar los estados de estos documentos de disponibilidad y registro presupuestal , de lo cual se comenta : 

- No existen documentos con esta información 😿 

- Se debe revisar el sistema SICAPITAL para poder abstraer los estados de este sistema

- Posteriormente se debe construir la historia de usuario para cada uno de los cambios de estados de CDP y CRP

**Comment by macaguegi** [comment]
En Sprint del día 27/09 se designa la tarea de estados de CDP y CRP al ingeniero @miguelramirex93 .

**Comment by macaguegi** [comment]
Se concreta modelo de datos en Mongo para Tipos de Compromiso . Se toma como referencia el documento suministrado por analista Maria Claudia [Tipos de Compromisos](https://drive.google.com/open?id=1vV8hSIbAkFqd4nDdVwcZ1PuToZ2AK3z9x0zlzwv3aUA)

**Categoría del Compromiso**
```json
{
    "_id": "242bdaoiro3r49r4",
    "nombre": "CONTRATO",
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}
```

**Tipo de Compromiso**
```json
{
    "_id": "68jsnvksjdkw0232",
    "idCategoria": "242bdaoiro3r49r4" ,
    "nombre": "CONTRATO DE OBRA",
    "descripcion": "Acuerdo temporal mediante el cual se contratar a un trabajador para que lleve a cabo un servicio concreto dentro de la empresa o una obra determinada.",
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}
```

** Compromiso**
```json
{
    "_id": "998vaajfoa2jfalfja",
    "idTipoCompromiso": "68jsnvksjdkw0232" ,
    "vigencia": "2019"
    "url": "http://www.contratacion.euskadi.eus/w32-1084/es/contenidos/anuncio_contratacion/expjaso6729/es_doc/adjuntos/otros1.pdf"
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}
```

Queda pendiente documentar el modelo en el repositorio y tambien la reunión con DBAs , Analistas y líder técnico @Filip9322 🐙

**Comment by mcrubianot** [comment]
Se revisa el día de hoy con el ingeniero Francisco en Sicapital y se establece que los estados que actualmente tienen los cdp y los crp son:

CDP
Argumento                  Resultado
AGOTADO -                 TOTAL COMPROMETIDO
VIGENTE-AGOTADO    PARCIALMENTE COMPROMETIDO
VIGENTE -                    VIGENTE
ANULADO -                 ANULADO

CRP
Argumento                  Resultado
AGOTADO                    TRAMITADO
VIGENTE-AGOTADO     PARCIALMENTE TRAMITADO
VIGENTE -                    VIGENTE
ANULADO -                 ANULADO

Considero pertinente el análisis por parte de los desarrollados de cada uno de estos estados para poder establecer las reglas que afectarán cada tipo de documento.

**Comment by macaguegi** [comment]
Se termina documentación y modelo de Compromisos . Se solicita revisión a @mcrubianot y a líder técnico @Filip9322 .  Estado tarea : 100%.

Las tareas de Estados de CDPs y CRPs quedan en manos del ingeniero José Miguel @miguelramirex93 y se puede continuar su respectivo seguimiento en el [Issue ](https://github.com/udistrital/plan_cuentas_mongo_crud/issues/100) :moneybag:

**Comment by mcrubianot** [comment]
Se revisa el https://github.com/udistrital/financiera_documentacion/blob/f/compromisos/gestion_egresos/Compromisos/modelo_datos_mongo.md
y cumple con lo establecido.

**Comment by mcrubianot** [comment]
Complemento mi nota anterior relacionada con los estados de los compromisos

https://docs.google.com/document/d/13gvoYbTTu9hzj7dmoj4NV2W-u_-KFPk9QYiXhuNM-jc/edit

**Comment by Soulfilip-UD** [comment]
Gracias @mcrubianot por tus observaciones y adjuntar el link de la documentación al issue .

Asimismo se revisa la documentación y modelo de datos , esta a tentativa de revisar el modelo de datos en la misma reunión de la socialización del modelo de datos de consecutivos [Link Issue](https://github.com/udistrital/financiera_documentacion/issues/35)

Tarea finalizada 
Proceeding to close Issue 👾
