### ISSUE TITLE
Socialización modelo de datos de Consecutivos - 1 hora - Felipe, Carlos y Miguel 

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#35]
Socializar y validar el modelo de datos planteado en el [Issue](https://github.com/udistrital/movimientos_crud/issues/33)

**Comment by Soulfilip-UD** [comment]
Reunión citada para el Jueves 3 de Octubre a las 9 am

**Comment by Soulfilip-UD** [comment]
Se realizo la reunión a las 10 am.

Quedaron las siguientes observaciones:

- [ ] Existe el servicio 'dominio' sobre el API de core_api, con este se puede contextualizar eventos a proyectos, subsistemas.

- [ ] Hacer un ejercicio exponiendo el modelo en relación al proyecto kronos, demostrando asimismo la afectación sobre el rubro.

El ejercicio se expondra el viernes 4 de Octubre

**Comment by Soulfilip-UD** [comment]
![md-consecutivos](https://user-images.githubusercontent.com/50924615/66458519-99264100-ea38-11e9-8dcd-c827653d413c.png)

**Comment by miguelramirez93** [comment]
Al realizar la socialización se definio que los consecutivos generados para este modelo deben estar atados a un encolador de peticiones para garantizar que no existan colisiones (consecutivos repetidos) por cada uno de los tipos de consecutivos que se puedan generar.

**Comment by corio27** [comment]
Aprobado

**Comment by nodier25** [comment]
Se revisa el modelo y cumple con los lineamientos

**Comment by jairolh** [comment]
verificado, ok

**Comment by Soulfilip-UD** [comment]
Modelo de datos, validado . Gracias @corio27 @jairolh @nodier25 

Tarea finalizada
Proceeding to close Issue :space_invader:
