### ISSUE TITLE
Socializar los tipos de compromisos - 1 hora

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#36]
Socialización de los tipo de compromisos con el analista

**Comment by macaguegi** [comment]
De acuerdo a la socialización con la analista @mcrubianot se concreta que el modelo solamente debería tener Categoría y Tipo de Compromiso.

**Categoría del Compromiso**
```json
{
    "_id": "242bdaoiro3r49r4",
    "nombre": "CONTRATO",
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}
```

**Tipo de Compromiso**
```json
{
    "_id": "68jsnvksjdkw0232",
    "idCategoria": "242bdaoiro3r49r4" ,
    "nombre": "CONTRATO DE OBRA",
    "descripcion": "Acuerdo temporal mediante el cual se contratar a un trabajador para que lleve a cabo un servicio concreto dentro de la empresa o una obra determinada.",
    "activo": true,
    "fechaCreacion": "2018-09-01T05:00:00Z",
    "fechaModificacion":"2018-09-01T05:00:00Z"
}
```
Queda pendiente reunión con Arquitectos y DBAs para proseguir con la implementación del modelo en el API Plan Cuentas Mongo :bee:

**Comment by Soulfilip-UD** [comment]
Se realiza la soicialización con el Analista y aprobado el funcionamiento , al realizar la socialización con los arquitectos y dba, se abstrae que los tipos de movimientos se pueden integrar al servicio de tipo_documento, por lo que se daria un dominio  especifico y se ingresarian o actualizaran los tipos de documentos

tarea Finalizada
Proceeding to close Issue 👾
