### ISSUE TITLE
Informe de análisis de Subsistema de Reportes

### ISSUE THREAD

**Issue by mcguegi** [udistrital/financiera_documentacion#4]
Se solicita :

- [x] Crear un informe escrito :page_facing_up: analizando las funcionalidades del Susbsistema de Reportes en el ambiente de pruebas del Sistema Financiero KRONOS

**Comment by macaguegi** [comment]
Se socializa con el líder técnico @Soulfilip-UD dudas acerca de los servicios a los que apunta el subsistema de Reportes ya que no se están generando documentos de CRP y CDP . Se concluye que se mirará la generación de documentos con ayuda de @juancsr .

**Comment by macaguegi** [comment]
Se adjunta enlace del informe [Informe de Subsistema de Reportes](https://docs.google.com/document/d/1rRLBZYnOFX0bG8nhJg7k8_HPgZwhiAbKD9r0hS_KQfY/edit?usp=sharing)

**Comment by macaguegi** [comment]
Se habla con el líder técnico @Soulfilip-UD y me indica  que la tarea se pospone para el mes Septiembre.
