### ISSUE TITLE
Planeación cierre subsistema presupuesto - Diana Ramirez, Maria Claudia y Felipe

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#40]
Ya que la planeación del cierre del subsistema se tenia planead para mediados de Octubre con el módulo de vigencia y cierre, se revisara el cronograma y se ajustaran fechas.

**Comment by DianaPatriciaRamirez** [comment]
Teniendo en cuenta la revisión realizada el día de hoy, respecto a la entrega funcional del hito 1 del Sistema Kronos (módulos: necesidades, rubros presupuestales, preasignación apropiación inicial y apropiaciones iniciales) y en la cual se observan aún muchos errores, se plantea una nueva revisión mañana 9 de octubre a las 11 a.m., en donde se espera tener solventadas todas las observaciones realizadas por @corio27 @mcrubianot y la jefe de la OAS Beatriz Jaramillo. 

Sin embargo, se solicita al líder técnico @Soulfilip-UD indicar la razón por la cual solicita modificación del cronograma.
