### ISSUE TITLE
Implementar recomendaciones de Seguridad

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#44]
J tras realizar sus pruebas de seguridad nos hace las siguientes recomendaciones

- [x]  Solicitar el análisis local de SonarQ
- [x] Actualizar README `necesidades_crud` 
- [x] Implementar las siguientes cabeceras 
`The anti-clickjacking X-Frame-Options header is not present.
The X-XSS-Protection header is not defined. This header can hint to the user agent to protect against some forms of XSS
The site uses SSL and the Strict-Transport-Security HTTP header is not defined.
The site uses SSL and Expect-CT header is not present.
The X-Content-Type-Options header is not set. This could allow the user agent to render the content of the site in a different fashion to the MIME type`

- [x] Limpieza de branches
     - [x] `plan_cuentas_mongo_crud`
     - [x] `movimientos_crud`
     - [x] `plan_cuentas_mid_crud`
     - [x] `necesidades_crud`
     - [x] `presupuesto_cliente`
     - [x] `necesidades_cliente`

## Para la entrega del hito 2 se requiere también

- [ ] Agregar el pipeline de pruebas desde el API
- [x] Finalizar pruebas unitarias `necesidades_crud`

**Comment by Soulfilip-UD** [comment]
Cabezeras
<img width="697" alt="Screen Shot 2019-11-22 at 8 34 45 AM" src="https://user-images.githubusercontent.com/50924615/69430259-2a105d80-0d03-11ea-9bb6-014ab6ef1014.png">

**Comment by DianaPatriciaRamirez** [comment]
Pendiente: 

- [ ] Radicar un nuevo kanban en TuLeap para pruebas de carga y estrés para el modulo de necesidades, indicando los servicios más críticos de deban pasar por estas pruebas.

- [ ] Enviar basic_tokens que define para la aplicación en el WSO2 al asesor de seguridad.

- [ ] Revisar proceso del despliegue de la maquina de sonarQ en AWS con Jhon Castellanos.

**Comment by Soulfilip-UD** [comment]
Tarjeta de tuleap
Pruebas #33938 Prueba de carga y estres Necesidades
https://tuleap.udistrital.edu.co/plugins/tracker/?aid=33938

**Comment by Soulfilip-UD** [comment]
Se realizo la documentación de `necesidades_crud`

**Comment by Soulfilip-UD** [comment]
`necesidades_cliente`
[Informe](https://docs.google.com/document/d/1ZXfs-h1_zBrCS22Xu3ZkPXX4NHjW6W-wamcpP6O-HaI/edit)
<img width="662" alt="Screen Shot 2019-12-06 at 1 19 34 AM" src="https://user-images.githubusercontent.com/50924615/70301175-a9079a80-17c7-11ea-985f-e524a66e6914.png">

**Comment by Soulfilip-UD** [comment]
`presupuesto_cliente`
[Informe](https://docs.google.com/document/d/1DbmxlpArgcgBiwa2pdMG17qZetDXyu3QzTHSwTo0SlA/edit#)
<img width="508" alt="Screen Shot 2019-12-06 at 1 29 28 AM" src="https://user-images.githubusercontent.com/50924615/70301300-fe43ac00-17c7-11ea-967b-03da2f47a47e.png">

**Comment by Soulfilip-UD** [comment]
`necesidades_crud`
[Informe](https://docs.google.com/document/d/1DbmxlpArgcgBiwa2pdMG17qZetDXyu3QzTHSwTo0SlA/edit#)
<img width="493" alt="Screen Shot 2019-12-06 at 1 29 20 AM" src="https://user-images.githubusercontent.com/50924615/70301341-161b3000-17c8-11ea-8466-2fc6ca3a77d2.png">

**Comment by Soulfilip-UD** [comment]
[Pruebas de Usabilidad](https://docs.google.com/document/d/1ZaeRxtZ0mJjd5Qdf9N8JQIifWcE8IEUkJrTkF-OaKUM/edit)

**Comment by Soulfilip-UD** [comment]
Los informes de pruebas realizadas por el experto en seguridad @jjvargass no han finalizado en un 100% ya que la prueba de funcionalidad no fue finalizada, aún así esta se debe realizar es cuando se esta realizando el paso a producción por lo que en el momento no son requeridas.

Aún así todas las demás pruebas sobre el sistema han salido con un diagnostico positivo de 0 vulnerabilidades por lo que se ha cumplido en un 100% con la tarea requerida.

Mientras se continue en desarrollo se requerira limpiar las ramas constantemente.

Tarea Finalizada
Proceeding to close Issue 👾

**Comment by DianaPatriciaRamirez** [comment]
Te recomiendo socializar con todo el equipo de desarrollo, arquitectos y gerente del proyecto; los resultados de las pruebas de seguridad realizadas para el módulo de gestión de necesidades. Para que estemos en línea manejando la misma información y con el fin de compartir experiencias y aprendizajes para los demas desarrollos.

**Comment by Soulfilip-UD** [comment]
https://github.com/udistrital/necesidades_crud/blob/dev/README.md

**Comment by DianaPatriciaRamirez** [comment]
Cuando ya no haya mas desarrollo del módulo de gestión de necesidades, garantizar el cumplimiento de las siguientes actividades para el paso de producción:

- [ ] Adjuntar los commits o evidencia de lo realizado.

- [ ] Link del analisis de SonarQ.

- [ ] Limpieza de branches permanente.

- [ ] Pruebas unitarias ya están pero no corrieron, el lider tecnico realizara la revision pertinente

**Comment by Soulfilip-UD** [comment]
[Informe SonarQ](https://sonarqube.portaloas.udistrital.edu.co/dashboard?id=necesidades_cliente)

**Comment by Soulfilip-UD** [comment]
A la fecha falta revisar el proceso que corre las pruebas unitarias para revisar porque fallan
