### ISSUE TITLE
Datos de prueba en Resoluciones para integración con CRP

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#46]
Datos de prueba en Resoluciones para integración con CRP

**Comment by BOTOOM** [comment]
El modulo de resoluciones actualmente consume el api antigua de `financiera`, dicha api apunta a una base de datos en postgres.

al momento de generar una resolución se consulta un CDP , el CDP es consultado del api de financiera (api antigua). y se asocia el `ID` del CDP.

al momento de habla con el líder técnico @Soulfilip-UD el comenta que ahora los CDP son generados en una nueva api , la cuestión es que el ID del api antigua es un ID numérico y el ID de la nueva base es un ID alfanumerico, por lo cual alli radica un problema, ya que la base de datos actual de resoluciones solo almacena ID numericos y habria conflictos al querer ingresar algo diferente a un numero, por para la integracion se tendria que modificar la base de datos de resoluciones y las apis, algo que tocaria realizar con sumo cuidado ya que puede generar muchos errores.

**Comment by Soulfilip-UD** [comment]
El equipo de Resoluciones debe adaptar el desarrollo para tomar en vez del id del CDP, el consecutivo. Realizando el anterior cambio aseguramos la integración ya que si dependen del id del CDP se entrara en conflicto dado que actualmente trabajamos con mongo y el formato puede ser demasiado irregular. Adjunto objeto ejemplo:


Movimiento CDP expedido
`{
    "_id" : "5ddc379b8e5cc100013f8718",
    "valor_actual" : 7500.0,
    "centro_gestor" : "1",
    "tipo" : "cdp",
    "fecha_registro" : "2019-11-25T20:20:42Z",
    "estado" : "expedido",
    "data" : {
        "some" : "data"
    },
    "afectacion_ids" : [ 
        "5ddc379b8e5cc100013f8719", 
        "5ddc379b8e5cc100013f871a"
    ],
    "valor_inicial" : 7500.0,
    "txn-revno" : NumberLong(3),
    "txn-queue" : [ 
        "5ddc379b8e5cc100013f871c_20b6a49c"
    ]
}`

**Comment by BOTOOM** [comment]
En nuestro equipo podemos realizar el cambio que solicita @Soulfilip-UD , durante el cambio haremos varias pruebas para verificar que todo siga funcionando correctamente.

apoyamos en que realizaremos el cambio, pero ahora mismo no podemos apoyar con ello, tenemos varias tareas que tiene una gran prioridad que debemos atender y terminar lo mas rápido posible. por ello me disculpo de no poder ayudar con ello inmediatamente.

en adición a lo anterior a manera de sugerencia y petición (en caso que ya lo tengan omitan todo este párrafo), pero seria bueno tener una buena cantidad de CDP similar a la que se cuenta hoy en día en el sistema que ya existía antes del uso de Mongo, o por lo menos varios con valores similares a los reales que se tiene  actualmente en las bases de test.

para finalizar, con respecto a las pruebas que se harán se deberá verificar si el cambio que se hara afectara a los datos ya existentes, e los cuales se usa el sistema existente antes del uso de Mongo. Esas son pruebas que se han de realizar para validar que el cambio se ha realizado de manera exitosa.

**Comment by Soulfilip-UD** [comment]
👍 se tendra en cuenta que resoluciones sigue en desarrollo y cuando requieran integrarse con Kronos para consultar los CDP deben pensar en que deben consultar un número, y para que la consulta de este sistema sea satisfactoria sin realizar mayores cambios debemos proveer un endpoint con el formato json que actualmente consumen.  Esto debido a que las apis antiguas de financiera no continuaran recibiendo soporte y a medida que se siga desarrollando los demas sistemas estos seguiran creando sus propios api desacoplados.

Tarea suspendida
