### ISSUE TITLE
Completar lineamientos de seguridad

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#49]
Basados en los siguientes items que hacen falta, quedan repartidas las tareas de tal forma:
<img width="960" alt="Screen Shot 2020-01-16 at 12 19 43 PM" src="https://user-images.githubusercontent.com/50924615/72547363-85218500-385a-11ea-8bcd-182ad442c581.png">

- [x] 1) Pruebas Unitarias en API CRUD movimientos_crud. CORE
- [x] 2) Control de Errores API MID (Respuestas Json) plan_cuentas_mid. Miguel Ramírez
- [x] 3) Pruebas Unitarias en API CRUD necesidades_crud. Neider Fajardo
- [x] 4) Pruebas Unitarias en API MID plan_cuentas_mid. Neider Fajardo
- [x] 5) Contenido README de plan_cuentas_mid y necesidades_cliente. Neider Fajardo
- [x] 6) Limpieza de Branches de plan_cuentas_mid y presupuesto_cliente. Felipe
- [x] 7) Pruebas Unitarias en API CRUD movimientos_crud. CORE
- [x] 8) 0 Bugs - 0 Vulnerabilidades. Maximo 50 % de Duplications. Felipe

**Comment by NeiderFajardo** [comment]
1.  Se complementan pruebas unitarias de [necesidades_crud](https://github.com/udistrital/necesidades_crud/issues/33)

2.  Se actualiza el contenido de los README en los siguientes repositorios para que se ajusten a los lineamientos estipulados por la oficina asesora de sistemas:

- Se complementa el contenido del README en [plan_cuentas_mongo_crud](https://github.com/udistrital/plan_cuentas_mongo_crud/pull/215)

- Se complementa el contenido del README en [plan_cuentas_mid](https://github.com/udistrital/plan_cuentas_mid/issues/139)

- Se complementa el contenido del README en [necesidades_crud](https://github.com/udistrital/necesidades_crud/pull/34)

- Se comolementa el contenido del README en [presupuesto_cliente](https://github.com/udistrital/presupuesto_cliente/pull/373)

- Se complementa el contenido del README en [contabilidad_cliente](https://github.com/udistrital/contabilidad_cliente/tree/dev)

**Comment by Soulfilip-UD** [comment]
Se realizan las pruebas unitarias faltantes para el API de necesidades_crud mas se esta revisando la ejecución de estas desde el local, una vez logre ejecutarlas doy el item por realizando.

Asimismo se confirma que todos los APIs listados contienen en el README un bloque sobre el modelo de negocio que manejan y se adjunto la licensia.
Como tarea adicional queda:
- [ ] Realizar el README de cuentas_contables_crud

Se limpian las ramas de :
- plan_cunetas_mongo_crud
- plan_cuentas_mid
- necesidades_cliente

**Comment by Soulfilip-UD** [comment]
Se creo la tarjeta de TULEAP para que el equipo del core realize el control de errores y pruebas unitarias del API movimientos_crud: https://tuleap.udistrital.edu.co/plugins/tracker/?aid=34394

Por defecto no permite la edición de la tarjeta por lo que no pude agregar información adicional en la descripción, aunque ya se requirio con la Steffany la edición para que quede claro el requisito.

**Comment by DianaPatriciaRamirez** [comment]
Por favor asignar el kanban al equipo CORE y describir exactamente cual es la solicitud.
![Captura de pantalla de 2020-01-17 12-17-01](https://user-images.githubusercontent.com/50375674/72631940-3ab80b00-3923-11ea-9995-526ae1326d95.png)

**Comment by DianaPatriciaRamirez** [comment]
@Soulfilip-UD Por favor revisa: https://github.com/udistrital/presupuesto_cliente/branches/all: 

- [ ] fix/plan-cuentas-route tiene error.
- [ ] revisar feature/router-links.

**Comment by miguelramirez93** [comment]
Según los comentarios realizados en el documento https://docs.google.com/document/d/15qdnj3Bah5JFSUuZ9dbgHoGMha8j_1dvYoXysAhgUJs

la realización del segmento de código:

```go
  defer func() {
		if r := recover(); r != nil {
			beego.Error(r)
			responseformat.SetResponseFormat(&c.Controller, r, "E_0459", 500)
		}
	}()
```
Afecta el seguimiento de errores dentro de los logs de los API. El use de los defer en go evita la utilización y repetición de código dentro de un mismo segmento. La sugerencia:

![image](https://user-images.githubusercontent.com/17803254/72743517-d17e0500-3b79-11ea-8b1f-96f2e3f58a24.png)

Tiene lineas y retornos repetidos. El defer permite solucionar esta parte tal como se esta manejnado qdentro del código de repositorio. Los print que se muestran en la sugerencia se asignan dentro de los panic para realizar el "seguimiento" sugerido.

**Comment by miguelramirez93** [comment]
Los lineamientos consignados en https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/control_error_json_crud.md estan definidos para CRUD's con postgres. Ya que Mongo y su "ORM" no especifica los mismos campos no se pueden definir JSON Schema iguales a los presentes en el anterior documento.

**Comment by NeiderFajardo** [comment]
Implementación de pruebas unitarias en plan_cuentas_mid
[PR](https://github.com/udistrital/plan_cuentas_mid/pull/144)

**Comment by Soulfilip-UD** [comment]
El projecto de necesidades_cliente al pasar por sonarqube arroja los siguientes resultados:
https://sonarqube.portaloas.udistrital.edu.co/dashboard?id=necesidades_cliente

<img width="736" alt="Screen Shot 2020-01-24 at 8 17 24 AM" src="https://user-images.githubusercontent.com/50924615/73071976-152a8480-3e82-11ea-9766-ba506319fa65.png">

Es difícil y es una tarea extensa asegurar que el repositorio tendrá 0 bugs sobre todo que es un cliente sobre tecnología relativamente antigua :angular 1 , el número de bugs es tan grande ya que corresponde a que sonarqube no detecta los mismo componentes de angular, y marca bugs sin razón.
<img width="751" alt="Screen Shot 2020-01-24 at 8 20 49 AM" src="https://user-images.githubusercontent.com/50924615/73072121-72bed100-3e82-11ea-8af4-c4ca5c524dea.png">

Y las vulnerabilidades que marca son por alerts o confirmaciones que se requirieron por parte del analista para confirmar el proceder de las acciones.
<img width="862" alt="Screen Shot 2020-01-24 at 8 17 10 AM" src="https://user-images.githubusercontent.com/50924615/73072203-a568c980-3e82-11ea-92dd-8a47c57733ae.png">

Y la duplicación del código esta en un 6.6% la cuál es buena.

Por lo que se cumple con los criterios de los lineamientos para su despliegue en producción.

**Comment by Soulfilip-UD** [comment]
Al día de hoy se realizaron las siguientes actividades:
 1) Pruebas Unitarias en API CRUD movimientos_crud. CORE [ok]
 2) Control de Errores API MID (Respuestas Json) plan_cuentas_mid. Miguel Ramírez [ok]
 3) Pruebas Unitarias en API CRUD necesidades_crud. Neider Fajardo [ok]
 4) Pruebas Unitarias en API MID plan_cuentas_mid. Neider Fajardo [ok]
 5) Contenido README de plan_cuentas_mid y necesidades_cliente. Neider Fajardo [ok]
 6) Limpieza de Branches de plan_cuentas_mid y presupuesto_cliente. Felipe [ok]
 7) Pruebas Unitarias en API CRUD movimientos_crud. CORE [ok]
 8) 0 Bugs - 0 Vulnerabilidades. Maximo 50 % de Duplications. Felipe [ok]

Hace falata realizar:
- [ ] Realizar el README de cuentas_contables_crud

**Comment by Soulfilip-UD** [comment]
Y se reviso las sugerencias que arrojaba el linter al desplegar plan_cuentas_mid y cuentas_contables_crud, estas se corrigieron por @NeiderFajardo  y solo se requiere aprobar los PR .
[PR #34 cuentas_contables_crud ](https://github.com/udistrital/cuentas_contables_crud/pull/34)
[PR #147 plan_cuentas_mid](https://github.com/udistrital/plan_cuentas_mid/pull/147)

**Comment by Soulfilip-UD** [comment]
Se realiza el README de cuentas_contables por parte de @NeiderFajardo , por lo que las tareas del Issue están completas.

Tarea finalizada
Proceeding to close Issue 👾
