### ISSUE TITLE
Levantamiento inventario Kronos

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_documentacion#50]

**Comment by mcrubianot** [comment]
De conformidad con reunión sostenida el día jueves 30 de abril de 2020, se establece con la Ing, Beatriz Elisa Jaramillo y la Ingeniera Diana Guayara, la tarea del levantamiento de información de los desarrollos que se llevan hasta el momento en el Sistema de Gestión Financiera Kronos.

Se me solicita tener en cuenta:
- Procedimientos sigud
- Procedimientos oas
- Historias de usuario
- Validación HU & Desarrollos

Una vez culminada dicha tarea se elaborará el cronograma de actividades a desarrollar.

**Comment by mcrubianot** [comment]
Se da inicio al levantamiento del inventario en el siguiente documento

https://docs.google.com/spreadsheets/d/1ayIVqtzfN1DvoDuAbECkU_Dw4_-OFBGLjfYWL0XFGJc/edit#gid=162619187

**Comment by mcrubianot** [comment]
Con el fin de validar los desarrollos frente a las HU se solicitó al Ingeniero John Castellano la información necesaria, quien me comunica las siguientes direcciones, usuarios y contraseñas

Subsistema de Necesidades
https://pruebasnecesidades.portaloas.udistrital.edu.co

Subsistema de Presupuesto
https://pruebaspresupuesto.portaloas.udistrital.edu.co

Usuario para ambos sistemas: pruebasoas
Contraseña: login(OAS);

**Comment by mcrubianot** [comment]
Se da inicio a la realización de la validación HU&Desarrollos.

Se registran dichas pruebas en el documento denominado 

Aplicación de Pruebas Funcionales y Usabilidad - Kronos 

https://docs.google.com/spreadsheets/d/1o6-_cJxkuaY4y3R_bk8DZ4CEf8Tp7_QdISyfULubmC8/edit#gid=0

**Comment by mcrubianot** [comment]
Se inicio el día 6  de marzo, la validación de desarrollo & historias de usuario del módulo de necesidades, se dejaron las observaciones en el documento 

https://docs.google.com/spreadsheets/d/1o6-_cJxkuaY4y3R_bk8DZ4CEf8Tp7_QdISyfULubmC8/edit#gid=0

**Comment by mcrubianot** [comment]
Se inicio la validación de desarrollo & historias de usuario del módulo de necesidades, se dejaron las observaciones en el documento

**Comment by corio27** [comment]
Se cambia estado

**Comment by mcrubianot** [comment]
Se inicio la validación de desarrollo & historias de usuario del Subsistema de Contabilidad, Tesorería, Central de cuentas y Reportes, dejando las observaciones en el siguiente documento

Subsistema de contabilidad 
https://docs.google.com/spreadsheets/d/1o6-_cJxkuaY4y3R_bk8DZ4CEf8Tp7_QdISyfULubmC8/edit#gid=360139185

Subsistema de Tesorería
https://docs.google.com/spreadsheets/d/1o6-_cJxkuaY4y3R_bk8DZ4CEf8Tp7_QdISyfULubmC8/edit#gid=463735325

Subsistema Central de Cuentas
https://docs.google.com/spreadsheets/d/1o6-_cJxkuaY4y3R_bk8DZ4CEf8Tp7_QdISyfULubmC8/edit#gid=389740467

Subsistema de Reportes
https://docs.google.com/spreadsheets/d/1o6-_cJxkuaY4y3R_bk8DZ4CEf8Tp7_QdISyfULubmC8/edit#gid=1906730320

**Comment by mcrubianot** [comment]
Se elabora el informe final del análisis en el siguiente documento

https://docs.google.com/document/d/1KYzo23Fg-Q0CUs5gZz9V9YySDY5bSNF-zlQdxNb3Q8s/edit
