### ISSUE TITLE
Analísis del documento y Diseño del Modelo de datos de Productos - Postgres

### ISSUE THREAD

**Issue by davidmm07** [udistrital/financiera_documentacion#6]
- [x] Generar .sql del modelo de datos de productos
- [x] Generar .dbm del modelo de productos
- [x] Documentar modelo en el repositorio

**Comment by Soulfilip-UD** [comment]
Tarea realizada y buena documentación!
Tras la migración a mongo, se debe modificar un poco el modelo de datos 

Proceeding to close Issue 👾

**Comment by davidmm07** [comment]
Modelo Postgres [Deprecated], ahora se usara el modelo del siguiente issue:
https://github.com/udistrital/plan_cuentas_mongo_crud/issues/37
