### ISSUE TITLE
Documentación despliegues - Jenkins, publisher, carbon. 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/financiera_documentacion#8]
- [x] Proceso de APIS  en jenkins
- [x] Proceso de clientes en jenkins
- [x] Proceso publisher
- [x] Proceso carbon

**Comment by Soulfilip-UD** [comment]
Tarea Realizada, queda por realizar un PR

**Comment by Soulfilip-UD** [comment]
La documentación queda consignada , más debido al cambio de procedimientos para el despliegue con test, es mejor realizar una nueva documentación.

Tarea revisada y lista para ser cerrada
Proceeding to close Issue 👾
