### ISSUE TITLE
Creación de Mockup's procesos de Productos 

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/financiera_documentacion#9]
Creación de los mockups de procesos de productos

- [x] Diseño de los mockups en la herramienta draw.io

- [x] Incluir el mockup en el repositorio de documentación del proyecto

**Comment by macaguegi** [comment]
Se añaden imagenes de mockups para Productos . Se pretende socializar los mismos con la analista Maria Claudia @mcrubianot y los arquitectos @jairolh  y @corio27 .

**Comment by macaguegi** [comment]
Se añade el enlace para ir a la herramienta DRAW.IO y visualizar la interacción 
[Draw.io](https://drive.google.com/file/d/1nBwIdN-Iue5I164bOOjwuNPBYWJMcBPB/view?usp=sharing)

**Comment by macaguegi** [comment]
Queda pendiente socialización con @juancsr sobre la asignación de productos a la hora de registrar Fuentes de Financiamiento

**Comment by macaguegi** [comment]
Se agrega el mockup de Asignación de Productos a una fuente de financiamiento y se procede a hacer la validación y socialización de este con @mcrubianot y con @juancsr ya que el se encuentra desarrollando el cliente de fuentes de financiamiento.

![AsignacionFuentes](https://user-images.githubusercontent.com/12780939/61542894-08773080-aa08-11e9-8ba5-28613e2c5e4e.png)

**Comment by Soulfilip-UD** [comment]
Mockups Realizados, y validados con el usuario

Proceeding to close Issue 👾
